(case :nil
	(0 (import "lib/debug/frames.inc"))
	(1 (import "lib/debug/profile.inc")))

(import "usr/env.inc")
(import "gui/lisp.inc")
(import "lib/consts/colors.inc")
(import "lib/net/url.inc")

(enums +select 0
	(enum main tip timer worker))

(enums +event 0
	(enum close max min)
	(enum lookup random))

(defq +event_hist_0 100 +event_syn_0 200 +event_ant_0 300
	+font_title (create-font "fonts/OpenSans-Bold.ctf" 14) +font_btn (create-font "fonts/OpenSans-Regular.ctf" 13)
	+font_bold (create-font "fonts/OpenSans-Bold.ctf" 13) +font_small (create-font "fonts/OpenSans-Regular.ctf" 11)
	+color_accent 0xff4361ee *config* :nil *config_version* 1
	*config_file* (cat *env_home* "lexicon.tre") *current_word* "lisp"
	*history* '("lisp" "computer" "algorithm") *current_phonetic* "" *current_defs* (list)
	*current_syns* (list) *current_ants* (list) *word_cache* (Fmap 63)
	*search_input* :nil *btn_lookup* :nil *btn_random* :nil
	*status_label* :nil *info_label* :nil *left_scroll* :nil
	*left_container* :nil *right_scroll* :nil *right_container* :nil)

(defq *random_words* '(
	"algorithm" "serendipity" "epiphany" "eloquent" "labyrinth"
	"luminous" "recursion" "paradigm" "solitude" "symphony"
	"nostalgia" "ethereal" "zenith" "catalyst" "heuristic"
	"velocity" "effervescent" "quixotic" "clandestine" "resilience"
	"cacophony" "sonorous" "pragmatic" "mellifluous" "halcyon"
	"surreptitious" "transcendent" "metamorphosis" "panacea" "ephemeral"
	"ubiquitous" "quintessential" "petrichor" "nefarious" "juxtaposition"
	"ineffable" "equilibrium" "idiosyncrasy" "conundrum" "anomaly"
	"audacious" "benevolent" "lucid" "vibrant" "nebula" "zenith"))

(defun config-default ()
	(scatter (Emap)
		:version *config_version*
		:last_word "lisp"
		:history '("lisp" "computer" "algorithm")))

(defun config-load ()
	(defq old_config :nil)
	(if (defq stream (file-stream *config_file*))
		(setq old_config (tree-load stream)))
	(if (or (not old_config) (/= (. old_config :find :version) *config_version*))
		(setq *config* (config-default))
		(setq *config* old_config))
	(setq *current_word* (. *config* :find :last_word))
	(if (not (str? *current_word*)) (setq *current_word* "lisp"))
	(setq *history* (. *config* :find :history))
	(if (not (list? *history*)) (setq *history* '("lisp" "computer" "algorithm"))))

(defun config-save ()
	(if (not *config*)
		(setq *config* (Emap)))
	(scatter *config*
		:version *config_version*
		:last_word *current_word*
		:history *history*)
	(when (defq stream (file-stream *config_file* +file_open_write))
		(tree-save stream *config*)))

(defun pos-label (tag)
	(case tag
		("n" "Noun")
		("v" "Verb")
		("adj" "Adjective")
		("adv" "Adverb")
		("u" "Interjection")
		(:t (upper (str tag)))))

(defun format-word-markdown (word phonetic defs syns ants)
	(defq lines (list (cat "# " (to-lower word)) ""))
	(when (and phonetic (nempty? (trim phonetic)))
		(push lines (cat "*Pronunciation:* `/" (trim phonetic) "/`") ""))
	(push lines "---" "")
	(if (empty? defs)
		(push lines "*No definitions found for this word.*" "")
		(progn
			(push lines "### Definitions" "")
			(defq count 1)
			(each (lambda ((pos_tag def_text))
				(push lines (cat (str count) ". **[" (pos-label pos_tag) "]** " def_text) "")
				(setq count (inc count)))
				defs)))
	(when (nempty? syns)
		(push lines "---" "" "### Synonyms" ""
			(cat (join syns ", ") ".") ""))
	(when (nempty? ants)
		(push lines "---" "" "### Antonyms" ""
			(cat (join ants ", ") ".") ""))
	lines)

(defun render-detail-pane (word phonetic defs syns ants)
	(each (# (. %0 :sub)) (. *right_container* :children))
	(bind '(sw &) (. *right_scroll* :get_size))
	(bind '(vsw &) (if (get :vslider *right_scroll*) (. (get :vslider *right_scroll*) :get_constraint) '(16 0)))
	(defq page_w (max 460 (- sw vsw 16)) md (Md)
		lines (format-word-markdown word phonetic defs syns ants))
	(def md :page_width page_w :zoom 1.0 :base_font_size 14)
	(. *right_container* :add_child md)
	(. md :populate_lines lines)
	(bind '(w h) (. *right_container* :pref_size))
	(. *right_container* :change_dirty 0 0 (max w page_w) h :t)
	(.-> *right_scroll* :layout :dirty_all))

(defun render-loading-pane (word)
	(each (# (. %0 :sub)) (. *right_container* :children))
	(defq lbl (Label))
	(def lbl :text (cat "Looking up " word "...") :font +font_btn :border 12 :ink_color +argb_grey8)
	(. *right_container* :add_child lbl)
	(bind '(& h) (. *right_container* :pref_size))
	(bind '(sw &) (. *right_scroll* :get_size))
	(bind '(vsw &) (if (get :vslider *right_scroll*) (. (get :vslider *right_scroll*) :get_constraint) '(16 0)))
	(defq cw (max 400 (- sw vsw)))
	(. *right_container* :change_dirty 0 0 cw (max h 60) :t)
	(.-> *right_scroll* :layout :dirty_all))

(defun render-left-pane ()
	(each (# (. %0 :sub)) (. *left_container* :children))
	(defq hist_hdr (Label))
	(def hist_hdr :text "Recent Searches" :font +font_bold :ink_color +argb_grey10 :border 4)
	(. *left_container* :add_child hist_hdr)
	(each (lambda (w)
		(defq idx (!) btn (Button) is_cur (eql (to-lower w) (to-lower *current_word*)))
		(def btn :text (cat " * " w) :font +font_btn :border (if is_cur 1 0))
		(when is_cur
			(def btn :color +color_accent :ink_color +argb_white))
		(. btn :connect (+ +event_hist_0 idx))
		(. *left_container* :add_child btn))
		*history*)
	(when (nempty? *current_syns*)
		(defq syn_hdr (Label))
		(def syn_hdr :text "Synonyms" :font +font_bold :ink_color +argb_grey10 :border 4)
		(. *left_container* :add_child syn_hdr)
		(each (lambda (s)
			(defq idx (!) btn (Button))
			(def btn :text (cat " ~ " s) :font +font_btn :border 0 :ink_color 0xff2e7d32)
			(. btn :connect (+ +event_syn_0 idx))
			(. *left_container* :add_child btn))
			*current_syns*))
	(when (nempty? *current_ants*)
		(defq ant_hdr (Label))
		(def ant_hdr :text "Antonyms" :font +font_bold :ink_color +argb_grey10 :border 4)
		(. *left_container* :add_child ant_hdr)
		(each (lambda (a)
			(defq idx (!) btn (Button))
			(def btn :text (cat " != " a) :font +font_btn :border 0 :ink_color 0xffc0392b)
			(. btn :connect (+ +event_ant_0 idx))
			(. *left_container* :add_child btn))
			*current_ants*))
	(bind '(& h) (. *left_container* :pref_size))
	(bind '(sw &) (. *left_scroll* :get_size))
	(bind '(vsw &) (if (get :vslider *left_scroll*) (. (get :vslider *left_scroll*) :get_constraint) '(16 0)))
	(defq cw (max 200 (- sw vsw)))
	(. *left_container* :change_dirty 0 0 cw h :t)
	(.-> *left_scroll* :layout :dirty_all))

(defun trigger-fetch-word (word worker_mbox)
	(def (. *status_label* :dirty) :text (cat "Looking up " word "..."))
	(. *status_label* :layout)
	(defq enc_word (url-encode word)
		def_url (cat "http://api.datamuse.com/words?sp=" enc_word "&md=dpr&max=1")
		syn_url (cat "http://api.datamuse.com/words?rel_syn=" enc_word "&max=10")
		ant_url (cat "http://api.datamuse.com/words?rel_ant=" enc_word "&max=8")
		task_code (str `(progn
			(import "service/net/app.inc")
			(import "lib/net/http.inc")
			(import "lib/net/json.inc")
			(ensure-net-service)
			(defq result :nil)
			(catch
				(progn
					(defq phonetic "" defs (list) syns (list) ants (list)
						resp (http-get ,def_url))
					(when resp
						(defq body (http-body-str resp))
						(when (and body (starts-with "[" (trim body)))
							(defq json (json-parse body))
							(when (and json (nempty? json))
								(defq entry (first json)
									raw_defs (or (pfind entry :defs) (list))
									tags (or (pfind entry :tags) (list)))
								(each (lambda (t_str)
									(if (starts-with "pron:" t_str)
										(setq phonetic (trim (slice t_str 5 -1)))))
									tags)
								(each (lambda (d_str)
									(defq tab_idx (find "\t" d_str))
									(if tab_idx
										(push defs (list (slice d_str 0 tab_idx) (slice d_str (inc tab_idx) -1)))
										(push defs (list "def" d_str))))
									raw_defs))))
					(defq s_resp (http-get ,syn_url))
					(when s_resp
						(defq s_body (http-body-str s_resp))
						(when (and s_body (starts-with "[" (trim s_body)))
							(defq s_json (json-parse s_body))
							(when (and s_json (nempty? s_json))
								(each (lambda (item)
									(if (defq sw (pfind item :word))
										(push syns sw)))
									s_json))))
					(defq a_resp (http-get ,ant_url))
					(when a_resp
						(defq a_body (http-body-str a_resp))
						(when (and a_body (starts-with "[" (trim a_body)))
							(defq a_json (json-parse a_body))
							(when (and a_json (nempty? a_json))
								(each (lambda (item)
									(if (defq aw (pfind item :word))
										(push ants aw)))
									a_json))))
					(setq result (list :lookup ,word phonetic defs syns ants)))
				(progn (setq result :nil) :t))
			(mail-send (hex-decode ,(hex-encode worker_mbox)) (str result)))))
	(open-child task_code +kn_call_run))

(defun select-word (word worker_mbox)
	(setq word (to-lower (trim word)))
	(when (nempty? word)
		(setq *current_word* word)
		(defq new_hist (list word))
		(each (lambda (w) (unless (eql (to-lower w) word) (push new_hist w))) *history*)
		(setq *history* (slice new_hist 0 (min (length new_hist) 15)))
		(config-save)
		(when *search_input*
			(.-> *search_input* (:set_text word) :layout :dirty))
		(defq cached (. *word_cache* :find word))
		(if cached
			(progn
				(bind '(phonetic defs syns ants) cached)
				(setq *current_phonetic* phonetic *current_defs* defs
					*current_syns* syns *current_ants* ants)
				(def (. *status_label* :dirty) :text "Cached")
				(def (. *info_label* :dirty) :text (cat word " | " (str (length defs)) " defs, " (str (length syns)) " syns"))
				(. *status_label* :layout) (. *info_label* :layout)
				(render-left-pane)
				(render-detail-pane word phonetic defs syns ants))
			(progn
				(setq *current_phonetic* "" *current_defs* (list)
					*current_syns* (list) *current_ants* (list))
				(render-left-pane)
				(render-loading-pane word)
				(trigger-fetch-word word worker_mbox)))))

(defun pick-random-word (worker_mbox)
	(defq idx (random (length *random_words*))
		word (elem-get *random_words* idx))
	(select-word word worker_mbox))

(ui-window *window* (:color +argb_grey15)
	(ui-title-bar _ "Lexicon - Dictionary & Thesaurus" (0xea19 0xea1b 0xea1a) +event_close)
	(ui-flow header_bar (:flow_flags +flow_right_fill :border 1)
		(ui-label _ (:text " LEX " :color +color_accent :ink_color +argb_white :font +font_title :border 1))
		(. (ui-textfield *search_input* (:color +argb_white :clear_text *current_word* :hint_text "Search word..." :font +font_btn :min_width 180))
			:connect +event_lookup)
		(. (ui-button *btn_lookup* (:text "Lookup" :font +font_btn :color +color_accent :ink_color +argb_white)) :connect +event_lookup)
		(. (ui-button *btn_random* (:text "Random" :font +font_btn)) :connect +event_random)
		(ui-label _ (:min_width 6 :border 0))
		(ui-label *status_label* (:text "Ready" :font +font_small :border 0 :ink_color +argb_grey8)))
	(ui-flow _ (:flow_flags +flow_up_fill)
		(ui-flow status_bar (:flow_flags +flow_right_fill :border 1)
			(ui-label _ (:min_width 8 :border 0))
			(ui-label *info_label* (:text "Ready" :font +font_small :border 0 :min_width 280)))
		(ui-flow main_split (:flow_flags +flow_right_fill)
			(ui-scroll *left_scroll* +scroll_flag_vertical (:min_width 220 :min_height 460)
				(ui-flow *left_container* (:flow_flags +flow_down_fill :color +argb_grey15)))
			(ui-scroll *right_scroll* +scroll_flag_vertical (:min_width 520 :min_height 460)
				(ui-flow *right_container* (:flow_flags +flow_down_fill :color +argb_grey15))))))

(defun main ()
	(config-load)
	(defq select (task-mboxes +select_size) *running* :t)
	(def *window* :tip_mbox (elem-get select +select_tip))
	(bind '(x y w h) (apply view-locate (. *window* :pref_size)))
	(gui-add-front-rpc (.-> *window* (:change x y w h :t) :dirty_all))
	(select-word *current_word* (elem-get select +select_worker))
	(while *running*
		(defq *msg* (mail-read (elem-get select (defq idx (mail-select select)))))
		(case idx
			(+select_worker
				(if (and *msg* (defq res (first (read (string-stream *msg*)))) (list?? res))
					(case (first res)
						(:lookup
							(bind '(& word phonetic defs syns ants) res)
							(. *word_cache* :insert word (list phonetic defs syns ants))
							(when (eql (to-lower word) (to-lower *current_word*))
								(setq *current_phonetic* phonetic *current_defs* defs
									*current_syns* syns *current_ants* ants)
								(def (. *status_label* :dirty) :text "Ready")
								(def (. *info_label* :dirty) :text (cat word " | " (str (length defs)) " defs, " (str (length syns)) " syns"))
								(. *status_label* :layout) (. *info_label* :layout)
								(render-left-pane)
								(render-detail-pane word phonetic defs syns ants))))
					(progn
						(def (. *status_label* :dirty) :text "Lookup failed")
						(.-> *status_label* :layout :dirty))))
			(+select_timer)
			(+select_tip
				(if (defq view (. *window* :find_id (getf *msg* +mail_timeout_id)))
					(. view :show_tip)))
			(+select_main
				(defq id (getf *msg* +ev_msg_target_id))
				(cond
					((= id +event_close)
						(setq *running* :nil))
					((= id +event_min)
						(bind '(x y w h) (apply view-fit (cat (. *window* :get_pos) (. *window* :pref_size))))
						(. *window* :change_dirty x y w h)
						(render-detail-pane *current_word* *current_phonetic* *current_defs* *current_syns* *current_ants*))
					((= id +event_max)
						(bind '(x y) (. *window* :get_pos))
						(bind '(mx my mw mh) (gui-info))
						(defq target_w (min 1200 (- mw 40)) target_h (min 800 (- mh 40)))
						(bind '(x y w h) (view-fit x y target_w target_h))
						(. *window* :change_dirty x y w h)
						(render-detail-pane *current_word* *current_phonetic* *current_defs* *current_syns* *current_ants*))
					((= id +event_lookup)
						(defq word (trim (. *search_input* :get_text)))
						(when (nempty? word)
							(select-word word (elem-get select +select_worker))))
					((= id +event_random)
						(pick-random-word (elem-get select +select_worker)))
					((and (>= id +event_hist_0) (< id (+ +event_hist_0 20)))
						(defq h_idx (- id +event_hist_0))
						(when (and (>= h_idx 0) (< h_idx (length *history*)))
							(select-word (elem-get *history* h_idx) (elem-get select +select_worker))))
					((and (>= id +event_syn_0) (< id (+ +event_syn_0 20)))
						(defq s_idx (- id +event_syn_0))
						(when (and (>= s_idx 0) (< s_idx (length *current_syns*)))
							(select-word (elem-get *current_syns* s_idx) (elem-get select +select_worker))))
					((and (>= id +event_ant_0) (< id (+ +event_ant_0 20)))
						(defq a_idx (- id +event_ant_0))
						(when (and (>= a_idx 0) (< a_idx (length *current_ants*)))
							(select-word (elem-get *current_ants* a_idx) (elem-get select +select_worker))))
					((. *window* :event *msg*))))))
	(config-save)
	(gui-sub-rpc *window*))
