(case :nil
	(0 (import "lib/debug/frames.inc"))
	(1 (import "lib/debug/profile.inc")))

(import "usr/env.inc")
(import "gui/lisp.inc")
(import "lib/consts/colors.inc")

(enums +event 0
	(enum close max min)
	(enum connect disconnect)
	(enum send))

(enums +select 0
	(enum main tip chat))

(defq +font_bold (create-font "fonts/OpenSans-Bold.ctf" 13)
	+font_btn (create-font "fonts/OpenSans-Regular.ctf" 13)
	+font_small (create-font "fonts/OpenSans-Regular.ctf" 11)
	*config_file* (cat *env_home* "chat.tre") *config_version* 1
	*config* :nil *history* (list) *max_display* 100 *max_history* 500
	entry :nil select :nil)

(ui-window *window* (:color +argb_grey15)
	(ui-title-bar *title* "Chat" (0xea19 0xea1b 0xea1a) +event_close)
	(ui-tool-bar *main_toolbar* ()
		(ui-buttons (0xe9ed 0xe9e8) +event_connect))
	(ui-flow user_bar (:flow_flags +flow_right_fill :border 1 :color +argb_white :ink_color +argb_black)
		(ui-label _ (:text "User:" :font +font_bold))
		(. (ui-textfield chat_user (:clear_text "" :hint_text "username" :font +font_btn))
			:connect +event_connect))
	(ui-scroll chat_scroll +scroll_flag_vertical (:min_width 480 :min_height 380)
		(ui-flow chat_flow (:flow_flags +flow_down_fill :color +argb_grey15)))
	(ui-flow input_bar (:flow_flags +flow_right_fill :border 1 :color +argb_white :ink_color +argb_black)
		(ui-label _ (:text "Chat:" :font +font_bold))
		(. (ui-textfield chat_text (:clear_text "" :hint_text "Type markdown message..." :font +font_btn))
			:connect +event_send)))

(defun config-default ()
	(scatter (Emap)
		:version *config_version*
		:username (or *env_user* "Guest")
		:max_display *max_display*
		:history (list)))

(defun config-load ()
	(defq old_config :nil)
	(if (defq stream (file-stream *config_file*))
		(setq old_config (tree-load stream)))
	(if (or (not old_config) (/= (. old_config :find :version) *config_version*))
		(setq *config* (config-default))
		(setq *config* old_config))
	(defq u (. *config* :find :username) md (. *config* :find :max_display)
		h (. *config* :find :history))
	(def chat_user :clear_text (if (and (str? u) (nempty? u)) u (or *env_user* "Guest")))
	(if (num? md) (setq *max_display* (max 20 md)))
	(setq *history* (if (list? h) h (list))))

(defun config-save ()
	(if (not *config*)
		(setq *config* (Emap)))
	(when (> (length *history*) *max_history*)
		(setq *history* (slice *history* (- (length *history*) *max_history*) -1)))
	(scatter *config*
		:version *config_version*
		:username (get :clear_text chat_user)
		:max_display *max_display*
		:history *history*)
	(when (defq stream (file-stream *config_file* +file_open_write))
		(tree-save stream *config*)))

(defun parse-chat-msg (raw_msg)
	(defq sender "System" body (trim (or raw_msg "") "\t\n\r "))
	(when (starts-with "<" body)
		(when (defq q2 (find ">" body))
			(setq sender (slice body 1 q2)
				body (trim (slice body (inc q2) -1) "\t\n\r "))))
	(list sender body))

(defun format-chat-lines (sender body)
	(cond
		((eql body "Has joined the chat !")
			(list (cat "**" sender "** *has joined the chat.*") "" "---"))
		((eql body "Has left the chat !")
			(list (cat "**" sender "** *has left the chat.*") "" "---"))
		(:t
			(defq lines (list (cat "**" sender "**") ""))
			(each (lambda (l) (push lines l)) (split body "\n"))
			(push lines "" "---")
			lines)))

(defun create-chat-md (sender body page_w)
	(defq lines (format-chat-lines sender body) md (Md))
	(def md :page_width page_w :zoom 1.0 :base_font_size 13)
	(. md :populate_lines lines)
	md)

(defun refresh-chat-layout ()
	(bind '(sw &) (. chat_scroll :get_size))
	(bind '(vsw &) (if (get :vslider chat_scroll) (. (get :vslider chat_scroll) :get_constraint) '(16 0)))
	(defq page_w (max 360 (- sw vsw 16)))
	(each (lambda (child)
		(when (Md? child)
			(def child :page_width page_w)
			(. child :render))) (. chat_flow :children))
	(bind '(w h) (. chat_flow :pref_size))
	(. chat_flow :change_dirty 0 0 (max w page_w) h :t)
	(. chat_flow :layout)
	(.-> chat_scroll :layout :dirty_all)
	(when (nempty? (. chat_flow :children))
		(. chat_scroll :visible (last (. chat_flow :children)))))

(defun add-chat-message (raw_msg &optional record_history)
	(bind '(sender body) (parse-chat-msg raw_msg))
	(bind '(sw &) (. chat_scroll :get_size))
	(bind '(vsw &) (if (get :vslider chat_scroll) (. (get :vslider chat_scroll) :get_constraint) '(16 0)))
	(defq page_w (max 360 (- sw vsw 16)))
	(while (>= (length (. chat_flow :children)) *max_display*)
		(. (first (. chat_flow :children)) :sub))
	(defq md (create-chat-md sender body page_w))
	(. chat_flow :add_child md)
	(bind '(w h) (. chat_flow :pref_size))
	(. chat_flow :change_dirty 0 0 (max w page_w) h :t)
	(. chat_flow :layout)
	(.-> chat_scroll :layout :dirty_all)
	(. chat_scroll :visible md)
	(when record_history
		(push *history* (cat "<" sender "> " body "\n"))
		(config-save)))

(defun render-history ()
	(each (# (. %0 :sub)) (. chat_flow :children))
	(bind '(sw &) (. chat_scroll :get_size))
	(bind '(vsw &) (if (get :vslider chat_scroll) (. (get :vslider chat_scroll) :get_constraint) '(16 0)))
	(defq page_w (max 360 (- sw vsw 16)))
	(if (empty? *history*)
		(progn
			(defq welcome (create-chat-md "System" "Welcome to ChrysaLisp Chat!\nType Markdown messages below (e.g. `**bold**`, `*italic*`, `` `code` ``).\nClick the **Join** button or press Enter on your username to connect." page_w))
			(. chat_flow :add_child welcome))
		(progn
			(defq entries (if (> (length *history*) *max_display*)
				(slice *history* (- (length *history*) *max_display*) -1) *history*))
			(each (lambda (raw)
				(bind '(sender body) (parse-chat-msg raw))
				(. chat_flow :add_child (create-chat-md sender body page_w))) entries)))
	(bind '(w h) (. chat_flow :pref_size))
	(. chat_flow :change_dirty 0 0 (max w page_w) h :t)
	(. chat_flow :layout)
	(.-> chat_scroll :layout :dirty_all)
	(when (nempty? (. chat_flow :children))
		(. chat_scroll :visible (last (. chat_flow :children)))))

(defun broadcast (text)
	(defq user (trim (get :clear_text chat_user)))
	(when (eql user "") (setq user (or *env_user* "Guest")))
	(setq text (cat "<" user "> " text "\n"))
	(each (# (mail-send (hex-decode (second (split %0 ","))) text)) (mail-enquire "*Chat")))

(defun connect-chat ()
	(defq user (trim (get :clear_text chat_user)))
	(when (eql user "") (setq user (or *env_user* "Guest")))
	(def chat_user :clear_text user)
	(unless entry
		(push select (mail-mbox))
		(setq entry (mail-declare (elem-get select +select_chat) "*Chat" "Chat Service 0.1"))
		(broadcast "Has joined the chat !"))
	(config-save))

(defun disconnect-chat ()
	(when entry
		(broadcast "Has left the chat !")
		(pop select)
		(mail-forget entry)
		(setq entry :nil))
	(config-save))

(defun tooltips ()
	(def *window* :tip_mbox (elem-get select +select_tip))
	(ui-tool-tips *main_toolbar*
		'("join" "leave")))

(defun main ()
	(setq select (task-mboxes (dec +select_size)))
	(tooltips)
	(config-load)
	(render-history)
	(bind '(x y w h) (apply view-locate (. *window* :pref_size)))
	(gui-add-front-rpc (. *window* :change x y w h))
	(defq running :t)
	(while running
		(defq *msg* (mail-read (elem-get select (defq idx (mail-select select)))))
		(cond
			((= idx +select_tip)
				(if (defq view (. *window* :find_id (getf *msg* +mail_timeout_id)))
					(. view :show_tip)))
			((= idx +select_chat)
				(add-chat-message *msg* :t))
			((= (defq id (getf *msg* +ev_msg_target_id)) +event_close)
				(setq running :nil))
			((= id +event_min)
				(bind '(x y w h) (apply view-fit (cat (. *window* :get_pos) (. *window* :pref_size))))
				(. *window* :change_dirty x y w h)
				(refresh-chat-layout))
			((= id +event_max)
				(bind '(x y) (. *window* :get_pos))
				(bind '(mx my mw mh) (gui-info))
				(defq target_w (min 1024 (- mw 40)) target_h (min 768 (- mh 40)))
				(bind '(x y w h) (view-fit x y target_w target_h))
				(. *window* :change_dirty x y w h)
				(refresh-chat-layout))
			((= id +event_connect)
				(connect-chat))
			((= id +event_disconnect)
				(disconnect-chat))
			((= id +event_send)
				(defq msg_text (trim (get :clear_text chat_text)))
				(when (nempty? msg_text)
					(unless entry
						(connect-chat))
					(broadcast msg_text)
					(set chat_text :clear_text "" :cursor 0 :anchor 0)
					(.-> chat_text :layout :dirty)))
			((. *window* :event *msg*))))
	(when entry
		(broadcast "Has left the chat !")
		(mail-forget entry))
	(config-save)
	(gui-sub-rpc *window*))
