;;;;;;;;;;;;;;;;
; char constants
;;;;;;;;;;;;;;;;

(defq
	+char_backspace 8
	+char_delete 127
	+char_tab 9
	+char_lf 10
	+char_cr 13
	+char_esc 27
	+char_space (ascii-code " ")
	+char_underscore (ascii-code "_")
	+char_pipe (ascii-code "|")
	+char_hash (ascii-code "#")
	+char_lrb (ascii-code "(")
	+char_rrb (ascii-code ")")
	+char_lsb (ascii-code "[")
	+char_rsb (ascii-code "]")
	+char_lcb (ascii-code "{")
	+char_rcb (ascii-code "}")
	+char_quote (ascii-code "'")
	+char_double_quote 34
	+char_tick (ascii-code "`")
	+char_comma (ascii-code ",")
	+char_tilda (ascii-code "~")
	+char_semi (ascii-code ";")
	+char_colon (ascii-code ":")
	+char_dot (ascii-code ".")
	+char_at (ascii-code "@")
	+char_lt (ascii-code "<")
	+char_gt (ascii-code ">")
	+char_equal (ascii-code "=")
	+char_plus (ascii-code "+")
	+char_minus (ascii-code "-")
	+char_multiply (ascii-code "*")
	+char_divide (ascii-code "/")
	+char_0 (ascii-code "0")
	+char_9 (ascii-code "9")
	+char_a (ascii-code "a")
	+char_A (ascii-code "A")
	+char_b (ascii-code "b")
	+char_B (ascii-code "B")
	+char_o (ascii-code "o")
	+char_O (ascii-code "O")
	+char_x (ascii-code "x")
	+char_X (ascii-code "X")
	+char_z (ascii-code "z")
	+char_Z (ascii-code "Z")
)
