(import "apps/system/login/env.inc")
(import "gui/lisp.inc")

(enums +event 0
	(enum close)
	(enum scramble solve)
	(enum click))

(enums +select 0
	(enum main tip))

(defq *config_file* (cat *env_home* "slider.tre")
	  *grid_w* 5
	  *grid_h* 5
	  *tile_count* (* *grid_w* *grid_h*)
	  *blank_value* (dec *tile_count*)
	  *board* (range 0 *tile_count*)
	  *solved_board* (range 0 *tile_count*)
	  *font* (create-font "fonts/OpenSans-Bold.ctf" 58)
	  *running* :t)

(ui-window *window* ()
	(ui-title-bar *title* "Slider Puzzle" (0xea19) +event_close)
	(ui-tool-bar *toolbar* ()
		(ui-buttons (0xe972 0xe923) +event_scramble))
	(ui-grid *grid* (:grid_width *grid_w* :grid_height *grid_h*
					 :color *env_window_col* :font *font*)
		(each (lambda (i)
			(. (ui-button _ (:min_width 80 :min_height 80))
			   :connect (+ +event_click i)))
			(range 0 *tile_count*)))
	(ui-label *status* (:text " " :flow_flags +flow_flag_align_hcenter)))

(defun tooltips ()
	(def *window* :tip_mbox (elem-get select +select_tip))
	(ui-tool-tips *toolbar* '("scramble" "solve")))

(defun config-load ()
	(defq loaded_board :nil)
	(if (defq stream (file-stream *config_file*))
		(setq loaded_board (tree-load stream)))
	(if (and loaded_board (= (length loaded_board) *tile_count*))
		(setq *board* loaded_board)
		(setq *board* (cat *solved_board*))))

(defun config-save ()
	(when (defq stream (file-stream *config_file* +file_open_write))
		(tree-save stream *board*)))

(defun get-char-for-val (v)
	(if (= v *blank_value*) "" (char (+ 65 v))))

(defun update-view ()
	(defq children (. *grid* :children))
	(defq i 0)
	(while (< i *tile_count*)
		(defq btn (elem-get children i))
		(defq val (elem-get *board* i))
		(def btn :text (get-char-for-val val))
		(if (= val *blank_value*)
			(def btn :color +argb_grey2)
			(def btn :color *env_toolbar_col*))
		(.-> btn (:constrain :t) :dirty)
		(++ i))
	(if (every eql *board* *solved_board*)
		(def *status* :text "SOLVED!" :color +argb_green)
		(def *status* :text " " :color *env_window_col*))
	(.-> *status* :layout :dirty))

(defun swap-tiles (i1 i2)
	(defq temp (elem-get *board* i1))
	(elem-set *board* i1 (elem-get *board* i2))
	(elem-set *board* i2 temp)
	(update-view))

(defun try-move (index)
	(defq blank-idx (find *blank_value* *board*))
	(defq ix (% index *grid_w*) iy (/ index *grid_w*)
		  bx (% blank-idx *grid_w*) by (/ blank-idx *grid_w*)
		  dist (+ (abs (- ix bx)) (abs (- iy by))))
	(when (= dist 1)
		(swap-tiles index blank-idx)))

(defun scramble ()
	(setq *board* (cat *solved_board*))
	(defq moves 0)
	(while (< moves 400)
		(defq blank-idx (find *blank_value* *board*)
			  bx (% blank-idx *grid_w*)
			  by (/ blank-idx *grid_w*)
			  candidates (list))
		(if (> bx 0) (push candidates (dec blank-idx)))
		(if (< bx (dec *grid_w*)) (push candidates (inc blank-idx)))
		(if (> by 0) (push candidates (- blank-idx *grid_w*)))
		(if (< by (dec *grid_h*)) (push candidates (+ blank-idx *grid_w*)))
		(swap-tiles blank-idx (elem-get candidates (random (length candidates))))
		(++ moves))
	(update-view))

(defun dispatch-action (id)
	(cond
		((= id +event_close)
			(setq *running* :nil))
		((= id +event_scramble)
			(scramble))
		((= id +event_solve)
			(setq *board* (cat *solved_board*))
			(update-view))
		((>= id +event_click)
			(try-move (- id +event_click)))))

(defun main ()
	(defq select (task-mboxes +select_size))
	(config-load)
	(tooltips)
	(bind '(x y w h) (apply view-locate (. *window* :pref_size)))
	(gui-add-front-rpc (. *window* :change x y w h))
	(update-view)
	(while *running*
		(defq msg (mail-read (elem-get select (defq idx (mail-select select)))))
		(cond
			((= idx +select_tip)
				(if (defq view (. *window* :find_id (getf msg +mail_timeout_id)))
					(. view :show_tip)))
			((= (getf msg +ev_msg_type) +ev_type_action)
				(dispatch-action (getf msg +ev_msg_target_id)))
			(:t (. *window* :event msg))))
	(config-save)
	(gui-sub-rpc *window*))
