(import "sys/lisp.inc")
(import "lib/pipe/pipe.inc")
(print)
(print "ChrysaLisp Installer v0.1")
(print "Building documentation and all platform boot images.")
(print "Please wait...")
(print)
(import "lib/pipe/pipe.inc")
(while (< (length (mail-nodes)) 9) (task-sleep 100000))
(pipe-run "make it" (lambda (_) (prin _) (stream-flush (io-stream "stdout"))))
(print)
(print "Install complete.")
(print "If on MacOS or Linux you may now run:")
(print "TUI with './run_tui.sh'")
(print "GUI with './run.sh'")
(print "If on Windows you may now run:")
(print "TUI with './run_tui.bat'")
(print "GUI with './run.bat'")
(print)
(print "Please press CNTRL-C to exit!")
(print)
