(defq *app_root* (path-to-file))
(import "usr/env.inc")
(import "gui/lisp.inc")
(import "lib/consts/colors.inc")
(import "lib/task/farm.inc")
(import "./app.inc")

(enums +select 0
	(enum main task reply timer tip))

(defq flicker_rate (/ 1000000 8) timer_rate (/ 1000000 1) max_move_time 10000000
	*running* :t start_time (pii-time) last_move_time 0 replys (list) next_seq 0
	selected_idx :nil legal_boards (list) history (list) redo_stack (list)
	color +white human_color +white brd "")

(import "./config.inc")
(import "./widgets.inc")
(import "./ui.inc")
(import "./actions.inc")

(defun valid-dests (selected_idx)
	(defq dests (list) piece (elem-get brd selected_idx))
	(each (lambda (lbrd)
		(when (eql (elem-get lbrd selected_idx) " ")
			(defq dest :nil)
			(each (lambda (i)
				(when (and (/= i selected_idx) (nql (elem-get lbrd i) (elem-get brd i)))
					(if (or (eql (elem-get lbrd i) piece)
							(and (eql piece "P") (find (elem-get lbrd i) "QRBN"))
							(and (eql piece "p") (find (elem-get lbrd i) "qrbn")))
						(setq dest i)))) (range 0 64))
			(if dest (push dests dest))))
		legal_boards)
	(unique dests))

(defun display-board (board)
	(defq dests (if selected_idx (valid-dests selected_idx) (list)))
	(each! (lambda (square piece)
		(defq i (!))
		(def square :text (elem-get
			(if (= (logand (+ i (>> i 3)) 1) 0) "wltvmoqkrbnp " "qkrbnpwltvmo ")
			(find piece "QKRBNPqkrbnp ")))
		(if (= (logand (+ i (>> i 3)) 1) 0)
			(defq paper +argb_white ink +argb_black)
			(defq paper +argb_black ink +argb_white))
		(if (eql i selected_idx)
			(setq paper +argb_yellow ink +argb_black))
		(if (find i dests)
			(setq paper +argb_green ink +argb_black))
		(def square :color paper :ink_color ink)
		(. square :constrain :t)) (list (. chess_grid :children) board) 0 64)
	(. chess_grid :dirty_all))

(defun vdu-print (vdu buf s)
	(each (lambda (c)
		(cond
			((eql c "\n")
				;line feed and truncate
				(if (> (length (push buf "")) (const vdu_height))
					(setq buf (slice buf (const (dec (neg vdu_height))) -1))))
			(:t ;char
				(elem-set buf -2 (cat (last buf) c))))) s)
	(. vdu :load buf 0 0 (length (last buf)) (dec (length buf))) buf)

(defun update-vdu ()
	(setq text_buf (vdu-print vdu (list "")
		(cat (LF) "Last Move: " (time-in-seconds last_move_time) " s" (LF)
			(if (= color +white) "White to move:" "Black to move:") (LF)))))

(defun dispatch-job (key val)
	(def val :timestamp (pii-time))
	(defq job_type (if (= color human_color) +job_type_get_moves +job_type_move))
	(mail-send (get :child val)
		(setf-> (cat (str-alloc +job_size) brd (apply (const cat) history))
			(+job_reply (elem-get select +select_reply))
			(+job_move_time max_move_time)
			(+job_type job_type)
			(+job_color color)))
	(update-vdu)
	(clear replys)
	(setq next_seq 0))

(defun create (key val nodes)
	(open-task (const (cat *app_root* "child.lisp")) (elem-get nodes (random (length nodes)))
		+kn_call_child key (elem-get select +select_task)))

(defun destroy (key val)
	(when (defq child (get :child val)) (mail-send child ""))
	(elem-set select +select_reply (mail-mbox)))

(defun dispatch-action (&rest action)
	(catch (eval action) (progn (prin _) (print) :t)))

(defun main ()
	(defq select (task-mboxes +select_size) farm :nil)
	(config-load)
	(def *window* :tip_mbox (elem-get select +select_tip))
	(display-board brd)
	(setq farm (Farm create destroy 1))
	(bind '(x y w h) (apply view-locate (. *window* :pref_size)))
	(gui-add-front-rpc (. *window* :change x y w h))
	(mail-timeout (elem-get select +select_timer) timer_rate 0)
	(while *running*
		(defq *msg* (mail-read (elem-get select (defq idx (mail-select select)))))
		(cond
			((= idx +select_tip)
				(if (defq view (. *window* :find_id (getf *msg* +mail_timeout_id)))
					(. view :show_tip)))
			((= idx +select_main)
				(defq target_id (getf *msg* +ev_msg_target_id))
				(cond
					((defq action (. *event_map* :find target_id))
						(dispatch-action action))
					((>= target_id +event_button)
						;board click
						(defq board_idx (- target_id +event_button))
						(if (= color human_color)
							(cond
								((eql selected_idx board_idx)
									;deselect
									(setq selected_idx :nil)
									(display-board brd))
								((find board_idx (if selected_idx (valid-dests selected_idx) (list)))
									;make move
									(defq target_board :nil piece (elem-get brd selected_idx))
									(each (lambda (lbrd)
										(when (and (eql (elem-get lbrd selected_idx) " ")
												(nql (elem-get lbrd board_idx) (elem-get brd board_idx)))
											(if (or (eql (elem-get lbrd board_idx) piece)
													(and (eql piece "P") (find (elem-get lbrd board_idx) "QRBN"))
													(and (eql piece "p") (find (elem-get lbrd board_idx) "qrbn")))
												(unless target_board (setq target_board lbrd)))))
										legal_boards)
									(setq selected_idx :nil legal_boards (list))
									(push history (setq color (neg color) brd target_board))
									(clear redo_stack)
									(display-board brd)
									(if farm (. farm :close))
									(setq last_move_time (- (pii-time) start_time) start_time (pii-time) farm (Farm create destroy 1)))
								(:t ;select piece
									(defq piece (elem-get brd board_idx) is_black (= color +black))
									(when (and (nql piece " ") (eql (< (code piece) (ascii-code "Z")) is_black))
										(setq selected_idx board_idx)
										(display-board brd)))))
						(. *window* :event *msg*))
					((and (not (Textfield? (. *window* :find_id target_id)))
							(= (getf *msg* +ev_msg_type) +ev_type_key_down)
							(> (getf *msg* +ev_msg_key_scode) 0))
						;key event
						(bind '(key mod) (getf-> *msg* +ev_msg_key_key +ev_msg_key_mod))
						(cond
							((bits? mod +ev_key_mod_control +ev_key_mod_alt +ev_key_mod_meta)
								(when (defq action (. *key_map_control* :find key)) (dispatch-action action)))
							((bits? mod +ev_key_mod_shift)
								(when (defq action (. *key_map_shift* :find key)) (dispatch-action action)))
							((defq action (. *key_map* :find key))
								(dispatch-action action))))
					(:t (. *window* :event *msg*))))
			((= idx +select_task)
				(defq key (getf *msg* +kn_msg_key) child (getf *msg* +kn_msg_reply_id))
				(when (and farm (defq val (. farm :find key)))
					(def val :child child)
					(dispatch-job key val)))
			((= idx +select_reply)
				(sort (push replys *msg*) (# (- (getf %1 +reply_seq) (getf %0 +reply_seq))))
				(while (and (/= (length replys) 0)
							(= (getf (last replys) +reply_seq) next_seq))
					(setq *msg* (pop replys) next_seq (inc next_seq))
					(defq data_type (getf *msg* +reply_type) data (slice *msg* +reply_data -1))
					(cond
						((= data_type (ascii-code "b"))
							(times 3
								(display-board brd)
								(task-sleep flicker_rate)
								(display-board data)
								(task-sleep flicker_rate))
							(push history (setq color (neg color) brd data))
							(clear redo_stack)
							(if farm (. farm :close))
							(setq last_move_time (- (pii-time) start_time) start_time (pii-time) farm (Farm create destroy 1)))
						((= data_type (ascii-code "m"))
							; ---> THIS PARTITION SIZE WAS 64, MUST BE 68 FOR CASTLING <---
							(setq legal_boards (partition data 68))
							(if farm (. farm :close))
							(setq farm :nil))
						((= data_type (ascii-code "e"))
							(setq text_buf (vdu-print vdu text_buf data))
							(if farm (. farm :close))
							(setq farm :nil))
						((= data_type (ascii-code "s"))
							(setq text_buf (vdu-print vdu text_buf data))))))
			(:t ;timer event
				(mail-timeout (elem-get select +select_timer) timer_rate 0)
				(if farm (. farm :refresh (+ max_move_time 2000000))))))
	(if farm (. farm :close))
	(config-save)
	(gui-sub-rpc *window*))
