(import "./exfat.inc")

(defun create-img ()
	(prin "Creating exfat.img (64MB)...")(print)
	(defq stream (file-stream "exfat.img" +file_open_write))
	(unless stream (throw "Failed to create file stream"))
	
	(defq fs (ExFat))
	
	;; Format 64MB
	(prin "Formatting...")(print)
	(. fs :format 64 stream)
	(prin "Formatted.")(print)
	
	;; Mount to add content
	(. fs :mount)
	(prin "Mounted.")(print)
	
	;; Create Directory
	(. fs :create_dir "/testdir")
	(prin "Created /testdir")(print)
	
	;; Create File
	(. fs :create_file "/readme.txt")
	(defq fh (. fs :open_file "/readme.txt" :write))
	
	(unless fh (throw "Failed to open /readme.txt"))
	
	(defq data "This is a test ExFAT image generated by ChrysaLisp.\n")
	(. fs :write_file fh data)
	(. fs :close_file fh)
	(prin "Created /readme.txt")(print)
	
	;; Create Nested File
	(. fs :create_file "/testdir/sub.txt")
	(setq fh (. fs :open_file "/testdir/sub.txt" :write))
	(if fh
		(progn
			(. fs :write_file fh "Content in subdirectory.\n")
			(. fs :close_file fh)
			(prin "Created /testdir/sub.txt")(print)
		)
	)
	
	(. fs :unmount)
	(prin "Unmounted.")(print)
	(prin "Image 'exfat.img' created successfully.")(print)
)

(catch
	(create-img)
	(progn (prin "Test Failed with exception: " _)(print) :t))

;clean exit
((ffi "service/gui/lisp_deinit"))
