(import "./exfat.inc")

(defun verify-img ()
	(prin "Verifying exfat.img...")(print)
	(defq stream (file-stream "exfat.img" +file_open_read))
	(unless stream (throw "Failed to open exfat.img"))
	
	(defq fs (ExFat))
	(set fs :stream stream)
	
	;; Mount
	(. fs :mount)
	(prin "Mounted exfat.img.")(print)
	
	;; Verify /readme.txt
	(prin "Verifying /readme.txt...")(print)
	(defq fh (. fs :open_file "/readme.txt" :read))
	(if fh
		(progn
			(defq content (. fs :read_file fh 100))
			(. fs :close_file fh)
			(prin " Content: '" content "'")(print)
			(if (eql content "This is a test ExFAT image generated by ChrysaLisp.\n")
				(progn (prin " /readme.txt verification SUCCESS")(print))
				(throw " /readme.txt verification FAILED" content))
		)
		(throw "Failed to open /readme.txt")
	)
	
	;; Verify /testdir/sub.txt
	(prin "Verifying /testdir/sub.txt...")(print)
	(defq fh (. fs :open_file "/testdir/sub.txt" :read))
	(if fh
		(progn
			(defq content (. fs :read_file fh 100))
			(. fs :close_file fh)
			(prin " Content: '" content "'")(print)
			(if (eql content "Content in subdirectory.\n")
				(progn (prin " /testdir/sub.txt verification SUCCESS")(print))
				(throw " /testdir/sub.txt verification FAILED" content))
		)
		(throw "Failed to open /testdir/sub.txt")
	)
	
	(. fs :unmount)
	(prin "Verification Completed Successfully.")(print)
)

(catch
	(verify-img)
	(progn (prin "Verification Failed with exception: " _)(print) :t))

;clean exit
((ffi "service/gui/lisp_deinit"))
