;import canvas class method slots
(defq slot_set_fbox nil slot_fill nil slot_swap nil)
(within-compile-env (lambda ()
	(import 'class/canvas/canvas.inc)
	(setq slot_set_fbox (method-slot 'canvas 'set_fbox)
		slot_fill (method-slot 'canvas 'fill)
		slot_swap (method-slot 'canvas 'swap))))

(defun read-farm (i s)
	(while (lt (length (elem i data)) s)
		(elem-set i data (cat (elem i data) (pipe-read (elem i farm)))))
	(defq _ (slice 0 s (elem i data)))
	(elem-set i data (slice s -1 (elem i data))) _)

(defun read-byte (o f)
	(code (elem o f)))
(defun read-short (o f)
	(add (read-byte o f) (bit-shl (read-byte (inc o) f) 8)))
(defun read-int (o f)
	(add (read-short o f) (bit-shl (read-short (add o 2) f) 16)))

(defun screen ((canvas w h s))
	(defq y 0 w (div (fmul w s) 1.0) h (div (fmul h s) 1.0)
		data (list) farm (list) com (list) line_length (mul w 4))
	(each (lambda (_)
		(push farm (pipe "lisp apps/raymarch/child.lisp"))
		(push data "")
		(push com (cat "(line " (str w) " " (str h)))) (range 0 8))
	(while (lt y h)
		(defq i (mod y (length farm)))
		(elem-set i com (cat (elem i com) (cat " " (str y))))
		(setq y (inc y)))
	(each (lambda (e c)
		(pipe-write e (cat c ") "))) farm com)
	(setq y 0)
	(while (lt y h)
		(defq _ (read-farm (mod y (length farm)) line_length) x 0)
		(while (lt x w)
			(call slot_set_fbox canvas (read-int (mul x 4) _) x y 1 1)
			(setq x (inc x)))
		(call slot_swap canvas)
		(setq y (inc y))))

(screen argv)
