;docs/ai_digest/crypto.md: what (aead-seal) makes, and what the tag is of
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'key (dia-box '("key, 32 bytes" "nonce, 12 bytes") 150 44 grey 11 :first) 0 0)
(dia-put s 'cha (dia-box '("ChaCha20" "a stream of blocks of 64 bytes," "from the key, the nonce and a count") 250 62 gold 11 :first) 210 -9)
(dia-put s 'b0 (dia-box '("block 0" "its start is the key of the tag") 220 44 gold 11 :first) 530 -40)
(dia-put s 'b1 (dia-box '("block 1 and on" "xor with the data") 220 44 gold 11 :first) 530 22)
(dia-put s 'poly (dia-box '("Poly1305" "of the aad, then what was encrypted," "then how long each was") 250 62 blue 11 :first) 810 -49)
(dia-put s 'enc (dia-box '("the data, encrypted" "as long as the data") 250 44 green 11 :first) 810 22)
(dia-put s 'tag (dia-box '("the tag" "16 bytes") 110 44 green 11 :first) 1120 -40)
(dia-join s 'key 'cha "")
(dia-join s 'cha 'b0 "")
(dia-join s 'cha 'b1 "")
(dia-join s 'b0 'poly "")
(dia-join s 'b1 'enc "")
(dia-join s 'poly 'tag "")
(dia-say s "what comes back from (aead-seal key nonce aad data): the two green parts, one str. The aad is guarded by the tag and is not in it." 0 124 11)
(dia-say s "(aead-open) makes the tag again from what it is given, and gives the data only if it is the tag it was given. A nonce is never used twice with a key." 0 140 11)
(diagram "aead_seal" (dia-scene-doc s))
