;docs/lisp/binding.md: what calling a function does with its arguments
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'call (dia-box "(test \qFred\q \qBlogs\q)" 220 34 grey 12 :t) 0 0)
(dia-put s 'args (dia-box '("the arguments, a list" "(\qFred\q \qBlogs\q)") 220 44 blue 11 :first) 0 70)
(dia-put s 'params (dia-box '("the parameters of test" "(a b)") 220 44 blue 11 :first) 260 70)
(dia-put s 'env (dia-box '("a new environment, (env-push)" "a  is  \qFred\q" "b  is  \qBlogs\q") 250 62 gold 11 :first) 115 160)
(dia-put s 'body (dia-box '("the body runs in it" "its last value is the result") 220 44 green 11 :first) 420 169)
(dia-put s 'pop (dia-box '("(env-pop)" "a and b are gone") 180 44 grey 11 :first) 440 250)
(dia-join s 'call 'args "")
(dia-join s 'args 'env "(bind)")
(dia-join s 'params 'env "")
(dia-join s 'env 'body "")
(dia-join s 'body 'pop "")
(dia-say s "(apply) does all of it. (bind) by itself does the middle of it, for a list of your own." 0 320 12 :nil 0xff202428)
(diagram "bind_call" (dia-scene-doc s))
