;docs/ai_digest/dynamic_code.md: Lisp that runs as the assembler does, and what is left to run
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-say s "as it is assembled" 0 -30 12 :t 0xff202428)
(dia-put s 'vp (dia-box '("gui/pixmap/class.vp" "(def-method :pixmap :to_argb32)" "calls (to-argb32 ...), plain Lisp") 240 62 grey 11 :first) 0 0)
(dia-put s 'gen (dia-box '("conv, for each channel" "makes a list of instructions" "for this pixel format") 220 62 gold 11 :first) 290 0)
(dia-put s 'pipe (dia-box '("pipeline" "zips the lists together," "(eval) of each instruction emits it") 240 62 gold 11 :first) 560 0)
(dia-join s 'vp 'gen "")
(dia-join s 'gen 'pipe "")
(dia-say s "as it runs" 0 110 12 :t 0xff202428)
(dia-put s 'call (dia-box '("(. pixmap :to_argb32 pixel 16)") 240 44 grey 11 :first) 0 140)
(dia-put s 'code (dia-box '("the method's body" "a flat run of shifts, ands and adds: no test of the format, no branch, no call") 510 44 green 11 :first) 290 140)
(dia-join s 'call 'code "")
(dia-join s 'pipe 'code "written into")
(dia-say s "None of the Lisp above is there when it runs. It ran once, and what it wrote is what runs." 0 210 11)
(diagram "compile_vs_run" (dia-scene-doc s))
