;docs/ai_digest/app_configuration.md: an app's configuration, from one run to the next
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'file (dia-box '("usr/<user>/app.tre" "an Emap as text, with a :version") 230 44 grey 11 :first) 250 0)
(dia-put s 'load (dia-box '("(config-load)" "as main starts") 170 44 blue 11 :first) 0 80)
(dia-put s 'default (dia-box '("(config-default)" "no file, a bad one, or" "another version") 180 62 gold 11 :first) 0 170)
(dia-put s 'run (dia-box '("*config*, while it runs" "the app reads and sets it") 220 44 green 11 :first) 255 80)
(dia-put s 'save (dia-box '("(config-save)" "as it closes: (config-update)," "then written") 190 62 blue 11 :first) 540 71)
(dia-join s 'file 'load "")
(dia-join s 'load 'run "")
(dia-join s 'load 'default "")
(dia-join s 'default 'run "")
(dia-join s 'run 'save "")
(dia-join s 'save 'file "")
(dia-say s "Read under a read lock and written under a write lock, so two apps do not meet in the file." 255 190 11)
(diagram "config_life" (dia-scene-doc s))
