;docs/ai_digest/docs_rendering.md: a page is made of sections, each by the handler for its tag
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'file (dia-box '("a .md file" "read a line at a time") 160 44 grey 11 :first) 0 70)
(dia-put s 'router (dia-box '("handler-func" "the tag of a fenced block," "or text") 180 62 gold 11 :first) 210 61)
(dia-put s 'load (dia-box '("handlers/tag.inc" "read and kept the first" "time a tag is met") 170 62 grey 11 :first) 215 170)
(each (lambda (i)
	(dia-put s (sym (cat "h" (str i))) (dia-box (elem-get '(("text" "an Md widget, a word a widget") ("vdu, code, file" "a Vdu or an editor") ("image" "a Canvas: .cpm .tga .svg .cwb") ("widget" "a live UI of an app")) i) 240 40 (if (= i 2) green blue) 11 :first) 440 (* i 50))
	(dia-join s 'router (sym (cat "h" (str i))) ""))
	'(0 1 2 3))
(dia-put s 'page (dia-box '("the page" "a Flow of them," "one under another") 150 62 grey 11 :first) 730 61)
(dia-join s 'file 'router "")
(dia-join s 'router 'load "")
(dia-join s 'h1 'page "")
(dia-join s 'h2 'page "")
(diagram "docs_sections" (dia-scene-doc s))
