;docs/ai_digest/chrysalisp_classes.md: a method call at the VP level and at the Lisp level
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-say s "VP: fixed at build time" 0 12 12 :t 0xff202428)
(dia-put s 'vobj (dia-box '("an object" "a struct: vtable, count, fields") 200 44 blue 11 :first) 0 24)
(dia-put s 'vtab (dia-box '("its class's vtable" "an array of function pointers," "the parent's slots first") 200 62 gold 11 :first) 0 100)
(dia-put s 'vfun (dia-box '("the function" "at a fixed offset") 200 44 green 11 :first) 0 194)
(dia-join s 'vobj 'vtab "at offset 0")
(dia-join s 'vtab 'vfun "add the method's offset, jump")
(dia-say s "Lisp: made as the program runs" 360 12 12 :t 0xff202428)
(dia-put s 'lobj (dia-box '("an object" "an :hmap of its properties") 220 44 blue 11 :first) 360 24)
(dia-put s 'ltab (dia-box '("*class_Button*, an :hmap" ":draw to its lambda ..., the parent's" "copied in when it was defined") 220 62 gold 11 :first) 360 100)
(dia-put s 'lfun (dia-box '("the lambda" "found by the symbol") 220 44 green 11 :first) 360 194)
(dia-join s 'lobj 'ltab ":vtable")
(dia-join s 'ltab 'lfun "look :draw up, call")
(dia-say s "The same idea twice. A Lisp class can be given a method, or have one changed, while it runs." 0 270 12 :nil 0xff202428)
(diagram "dual_vtable" (dia-scene-doc s))
