;docs/apps/editor.md: every key and click of the Editor goes through one function
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'in (dia-box '("a key, a click, a toolbar button" "*key_map*, *key_map_shift*, *key_map_control*, *event_map*") 430 44 grey 11 :first) 60 0)
(dia-put s 'dispatch (dia-box '("(dispatch-action)" "app_impl.lisp") 220 44 gold 11 :first) 165 84)
(dia-put s 'macro (dia-box '("the macro recorder" "notes the action," "if one is being recorded") 170 62 blue 11 :first) 0 170)
(dia-put s 'undo (dia-box '("the undo tracker" "marks where this" "step begins") 170 62 blue 11 :first) 190 170)
(dia-put s 'cursor (dia-box '("the cursor stack" "where the cursor was," "to go back to") 170 62 blue 11 :first) 380 170)
(dia-put s 'run (dia-box '("the action runs" "(action-insert), (action-save) ...") 260 44 green 11 :first) 145 276)
(dia-join s 'in 'dispatch "")
(dia-join s 'dispatch 'macro "")
(dia-join s 'dispatch 'undo "")
(dia-join s 'dispatch 'cursor "")
(dia-join s 'macro 'run "")
(dia-join s 'undo 'run "")
(dia-join s 'cursor 'run "")
(diagram "editor_dispatch" (dia-scene-doc s))
