;docs/apps/editor.md: the parts of the Editor, a model, views and a controller
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'service (dia-box '("the @Edit service" "other apps ask it to open a file" "and go to a line") 220 62 grey 11 :first) 380 0)
(dia-put s 'ctrl (dia-box '("app_impl.lisp" "the controller: the event loop," "(dispatch-action)") 220 62 gold 11 :first) 110 0)
(dia-put s 'widgets (dia-box '("widgets.inc" "the view: the window," "its toolbars and trees") 190 62 blue 11 :first) 0 110)
(dia-put s 'ui (dia-box '("ui.inc" "Editor-edit, an Edit widget" "for this app") 200 62 blue 11 :first) 230 110)
(dia-put s 'layers (dia-box '("the Edit widget's layers" "Vdu: glyphs, and masks for" "the selection and brackets") 200 62 blue 11 :first) 230 212)
(dia-put s 'doc (dia-box '("Document" "the model: the text, the cursors," "the undo and redo stacks") 220 62 green 11 :first) 220 314)
(dia-join s 'service 'ctrl "RPC")
(dia-join s 'ctrl 'widgets "")
(dia-join s 'ctrl 'ui "")
(dia-join s 'ui 'layers "")
(dia-join s 'layers 'doc "its :buffer")
(dia-say s "An action changes the Document, each change a step of its undo;" 470 330 11)
(dia-say s "the controller then has the widget draw what the Document now is." 470 346 11)
(diagram "editor_architecture" (dia-scene-doc s))
