;docs/ai_digest/vp64_emu.md: the state of the emulator and the loop that runs it
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'fetch (dia-box '("fetch" "a 16 bit instruction, ir," "from where pc points") 190 62 blue 11 :first) 0 0)
(dia-put s 'decode (dia-box '("decode" "ir & 0xff is the opcode," "the rest is registers and constants") 220 62 blue 11 :first) 250 0)
(dia-put s 'exec (dia-box '("execute" "one switch, a case an opcode;" "more words are taken from pc if needed") 240 62 gold 11 :first) 530 0)
(dia-join s 'fetch 'decode "")
(dia-join s 'decode 'exec "")
(dia-put s 'regs (dia-box '("regs[16]" "64 bit integers" "regs[15] is the stack pointer") 190 62 green 11 :first) 0 130)
(dia-put s 'fregs (dia-box '("fregs[16]" "64 bit IEEE doubles") 220 62 green 11 :first) 250 130)
(dia-put s 'flags (dia-box '("pc, and what was compared" "compare1, compare2," "compare_f1, compare_f2") 240 62 green 11 :first) 530 130)
(dia-join s 'exec 'flags "reads and writes")
(dia-say s "and round again, till the program ends" 250 84 11)
(dia-say s "The whole state of the machine. The stack is a block of memory regs[15] starts at the top of, and it grows down." 0 214 11)
(diagram "emu_loop" (dia-scene-doc s))
