;docs/lisp/environment.md: the environments a running function can see, each the child of the one it was called from
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'boot (dia-box '("the boot environment" "class/lisp/root.inc, shared by every Lisp task" "defun, map, cat ...") 330 62 grey 11 :first) 0 0)
(dia-put s 'task (dia-box '("the task's environment" "stdio, args, what the app defined at its top") 330 46 blue 11 :first) 0 92)
(dia-put s 'outer (dia-box '("a function that was called" "its parameters, its (defq)s") 330 46 green 11 :first) 0 168)
(dia-put s 'inner (dia-box '("the function it called, running now" "its parameters, its (defq)s") 330 46 gold 11 :first) 0 244)
(dia-join s 'inner 'outer "(penv)")
(dia-join s 'outer 'task "(penv)")
(dia-join s 'task 'boot "(penv)")
(dia-say s "(defq) (bind) (def) (def?)" 370 262 12 :t 0xff202428)
(dia-say s "this environment only" 370 278 11)
(dia-say s "(setq) (set) (get), and a symbol that is evaluated" 370 120 12 :t 0xff202428)
(dia-say s "look here, then in each parent in turn, to the first that has it." 370 136 11)
(dia-say s "So a function sees what its caller had. Scope is dynamic." 370 152 11)
(diagram "environment_chain" (dia-scene-doc s))
