;docs/gui/event_loops.md: an app's event loop, a mailbox for each kind of thing that can come
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'gui (dia-box '("GUI task" "mouse, keys, widgets") 150 44 grey 11 :first) 0 0)
(dia-put s 'clock (dia-box '("(mail-timeout)" "a time that has come") 150 44 grey 11 :first) 0 64)
(dia-put s 'child (dia-box '("a child task" "its answer") 150 44 grey 11 :first) 0 128)
(dia-put s 'm0 (dia-box '("main" "+select_main 0") 130 44 blue 11 :first) 220 0)
(dia-put s 'm1 (dia-box '("timer" "+select_timer 1") 130 44 blue 11 :first) 220 64)
(dia-put s 'm2 (dia-box '("reply" "+select_reply 2") 130 44 blue 11 :first) 220 128)
(dia-say s "the select list, a mailbox each" 220 196 11)
(dia-put s 'select (dia-box '("(mail-select select)" "waits, gives the index" "of one that has mail") 170 64 gold 11 :first) 420 54)
(dia-put s 'read (dia-box '("(mail-read ...)" "the message") 130 44 0xffffffff 11 :first) 650 64)
(dia-put s 'cond (dia-box '("(cond ((= idx ...)" "what came, by which" "mailbox it came to") 170 64 green 11 :first) 630 150)
(dia-join s 'gui 'm0 "")
(dia-join s 'clock 'm1 "")
(dia-join s 'child 'm2 "")
(dia-join s 'm0 'select "")
(dia-join s 'm1 'select "")
(dia-join s 'm2 'select "")
(dia-join s 'select 'read "idx")
(dia-join s 'read 'cond "")
(dia-say s "The earlier a mailbox is in the list, the sooner its mail is taken. No message needs to say what kind it is." 0 250 12 :nil 0xff202428)
(diagram "event_loop" (dia-scene-doc s))
