;docs/gui/event_dispatch.md: from the mouse to the function of the app that acts on it
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'host (dia-box '("host" "mouse, keys") 100 44 grey 11 :first) 0 0)
(dia-put s 'gui (dia-box '("GUI task" "finds the view under it," "and who owns that view") 170 60 grey 11 :first) 140 -8)
(dia-put s 'main (dia-box '("the app's main mailbox" "an event, +ev_msg_target_id") 190 44 blue 11 :first) 350 0)
(dia-put s 'window (dia-box '("(. window :event msg)" "id below 0: a widget's own") 190 44 0xffffffff 11 :first) 350 80)
(dia-put s 'widget (dia-box '("the widget" ":mouse_down, :mouse_up ..." "then (. this :emit)") 170 60 green 11 :first) 140 72)
(dia-put s 'action (dia-box '("an action event" "the id the app gave with" "(. view :connect id)") 170 60 gold 11 :first) 140 160)
(dia-put s 'dispatch (dia-box '("*event_map*" "id to function" "(dispatch-action)") 170 60 green 11 :first) 450 160)
(dia-put s 'func (dia-box '("(action-...)" "the app's function") 140 44 blue 11 :first) 660 168)
(dia-join s 'host 'gui "")
(dia-join s 'gui 'main "")
(dia-join s 'main 'window "")
(dia-join s 'window 'widget "")
(dia-join s 'widget 'action "")
(dia-join s 'action 'dispatch "through main again")
(dia-join s 'dispatch 'func "")
(diagram "event_dispatch" (dia-scene-doc s))
