;docs/ai_digest/fault_tolerant.md: a branch of the tree of tasks is lost and made again
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6 red 0xfff7d7d7)
(dia-put s 'root (dia-box '("the root task" "a mailbox for each branch") 420 44 gold 11 :first) 110 0)
(dia-put s 'a (dia-box '("a child" "works, answers") 130 44 blue 11 :first) 60 100)
(dia-put s 'b (dia-box '("a child, its node gone" "no answer in time") 180 44 red 11 :first) 200 100)
(dia-put s 'c (dia-box '("made again, elsewhere" "answers to a new mailbox") 200 44 green 11 :first) 390 100)
(dia-put s 'old (dia-box '("the old mailbox" "let go of") 130 44 grey 11 :first) 225 196)
(dia-join s 'root 'a "")
(dia-join s 'root 'b "" :none)
(dia-join s 'root 'c "")
(dia-join s 'b 'old "anything it still says")
(dia-say s "Nothing keeps track of what was lost. What a lost branch says late" 370 206 11)
(dia-say s "goes to a mailbox nobody reads, and the new one starts clean." 370 222 11)
(diagram "fault_tree" (dia-scene-doc s))
