;docs/ai_digest/keeping_it_hot.md: what happens when (my-func arg0 arg1) is evaluated
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'site (dia-box '("the call site" ":lisp :repl_eval") 240 44 grey 11 :first) 0 0)
(dia-put s 'op (dia-box '("1  look at the operator") 240 34 gold 11) 0 70)
(dia-put s 'args (dia-box '("2  evaluate the arguments" "an args list from the chain") 240 44 gold 11 :first) 0 130)
(dia-put s 'scope (dia-box '("3  take a scope, env_push" "an environment from the chain") 240 44 gold 11 :first) 0 200)
(dia-put s 'bind (dia-box '("4  bind the parameters, env_bind" "sets each symbol's +str_hashslot") 240 44 gold 11 :first) 0 270)
(dia-put s 'body (dia-box '("5  run the body, repl_progn" "variables read straight from their slots") 240 44 green 11 :first) 0 340)
(dia-put s 'unscope (dia-box '("6  give the scope back, env_pop") 240 34 gold 11) 0 410)
(dia-put s 'ret (dia-box "the value, to the caller" 240 34 grey 11) 0 470)
(dia-put s 'special (dia-box '("a special form" "jump to its native code") 190 44 blue 11 :first) 330 65)
(dia-put s 'native (dia-box '("a built in function" "call its native code") 190 44 blue 11 :first) 330 130)
(dia-put s 'argsback (dia-box "the args list, back to the chain" 220 34 0xffffffff 11) 330 275)
(dia-join s 'site 'op "")
(dia-join s 'op 'args "")
(dia-join s 'args 'scope "a lambda")
(dia-join s 'scope 'bind "")
(dia-join s 'bind 'body "")
(dia-join s 'body 'unscope "")
(dia-join s 'unscope 'ret "")
(dia-join s 'op 'special "")
(dia-join s 'args 'native "")
(dia-join s 'bind 'argsback "")
(dia-join s 'native 'argsback "after")
(diagram "hot_call" (dia-scene-doc s))
