;docs/lisp/macros.md: a macro is a function that is called as the source is read
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'src (dia-box '("source text" "(ascii-code \qM\q)") 170 44 grey 11 :first) 0 20)
(dia-put s 'read (dia-box '("(read)" "a tree of lists") 130 44 blue 11 :first) 210 20)
(dia-put s 'expand (dia-box '("(macroexpand)" "a list that begins with a macro is" "put in place of by what the macro gives") 250 62 gold 11 :first) 380 11)
(dia-put s 'tree (dia-box '("the tree that is left" "77") 170 44 grey 11 :first) 420 110)
(dia-put s 'eval (dia-box '("(eval)" "runs it, as often as it is run") 200 44 green 11 :first) 170 110)
(dia-join s 'src 'read "")
(dia-join s 'read 'expand "")
(dia-join s 'expand 'tree "")
(dia-join s 'tree 'eval "")
(dia-say s "once, as it is read" 400 96 11)
(dia-say s "The macro's work is done once, before the code runs. What runs is only what it left behind." 0 190 12 :nil 0xff202428)
(diagram "macro_time" (dia-scene-doc s))
