;docs/intro/mesh.md: three machines that have joined
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(each (lambda (i)
	(defq x (elem-get '(0 250 500) i) y (elem-get '(110 0 110) i))
	(dia-put s (sym (cat "m" (str i))) (dia-box (list (elem-get '("a Mac" "another Mac" "a Raspberry Pi") i) "mesh -j" "the same mesh_key") 170 62 (if (= i 1) gold blue) 11 :first) x y))
	'(0 1 2))
(dia-join s 'm0 'm1 "" :both)
(dia-join s 'm1 'm2 "" :both)
(dia-join s 'm0 'm2 "a link each way they can reach" :both)
(dia-say s "mesh -j listens, link -l 3333 -a, says it is there, and looks for the others, link -a." 0 210 11)
(dia-say s "A machine with a mesh_key links only to one that proves it has the same key." 0 226 11)
(dia-say s "Once joined, every node of every machine is one network: mail goes between them, and a task can be sent to a node of another." 0 250 12 :nil 0xff202428)
(diagram "mesh_join" (dia-scene-doc s))
