;docs/vm/vp_structure.md: the life of a VP object
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6 red 0xfff7d7d7)
(dia-put s 'create (dia-box '(":create" "with what it is made from") 180 44 gold 11 :first) 0 0)
(dia-put s 'alloc (dia-box '(":sys_mem :alloc" "a cell of memory") 160 44 grey 11 :first) 220 0)
(dia-put s 'init (dia-box '(":init" "its fields set, the count 1") 180 44 green 11 :first) 420 0)
(dia-put s 'live (dia-box '("in use" ":ref adds one to the count," ":deref takes one off") 220 62 blue 11 :first) 400 90)
(dia-put s 'destroy (dia-box '(":destroy" "when the count is 0") 160 44 red 11 :first) 200 99)
(dia-put s 'deinit (dia-box '(":deinit" "lets go of what it holds") 180 44 red 11 :first) 190 190)
(dia-put s 'free (dia-box '(":sys_mem :free" "the cell, back to its heap") 180 44 grey 11 :first) 410 190)
(dia-join s 'create 'alloc "")
(dia-join s 'alloc 'init "")
(dia-join s 'init 'live "")
(dia-join s 'live 'destroy "")
(dia-join s 'destroy 'deinit "")
(dia-join s 'deinit 'free "")
(dia-say s "Whoever keeps a pointer to an object takes a :ref, and gives it up with a :deref. Nothing is collected later." 0 266 12 :nil 0xff202428)
(diagram "object_life" (dia-scene-doc s))
