;docs/ai_digest/pipe_commands.md: a pipeline, each command a task that may be on another node
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'term (dia-box '("Terminal, or (pipe-run)" "files . .lisp | grep defun | sort") 250 44 gold 11 :first) 200 0)
(each (lambda (i)
	(dia-under s (dia-box "" 190 96 grey) (* i 230) 90)
	(dia-say s (cat "a node") (+ (* i 230) 10) 106 11)
	(dia-put s (sym (cat "c" (str i))) (dia-box (list (elem-get '("files" "grep" "sort") i) "a task: stdin, stdout, stderr") 170 44 blue 11 :first) (+ (* i 230) 10) 114))
	'(0 1 2))
(dia-join s 'c0 'c1 "stdout")
(dia-join s 'c1 'c2 "stdout")
(dia-join s 'term 'c0 "starts each" :none)
(dia-join s 'c2 'term "the last stdout, and every stderr")
(dia-say s "Each | is an :out stream to an :in stream, in order whatever route the mail takes." 0 220 11)
(dia-say s "With | a command may be started on any node, with ! it is kept on this one." 0 236 11)
(diagram "pipe_line" (dia-scene-doc s))
