;docs/ai_digest/rack.md: what rack "tests -a" does on three machines
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(each (lambda (i)
	(defq x (* i 300))
	(dia-under s (dia-box "" 220 190 grey) x 0)
	(dia-say s (elem-get '("this machine" "another" "and another") i) (+ x 12) 20 12 :t 0xff202428)
	(dia-put s (sym (cat "m" (str i))) (dia-box '("member" "./rack.sh up" "in the mesh, takes a sync") 190 58 (if (= i 0) gold blue) 11 :first) (+ x 15) 32)
	(dia-put s (sym (cat "f" (str i))) (dia-box '("a fresh session" "on the boot image as it is now" "runs the tests, and goes") 190 58 green 11 :first) (+ x 15) 118)
	(dia-join s (sym (cat "m" (str i))) (sym (cat "f" (str i))) "starts"))
	'(0 1 2))
(dia-join s 'm0 'm1 "sync" :none)
(dia-join s 'm1 'm2 "sync" :none)
(dia-say s "1  the trees of the others are made the same as this one's, sync" 0 216 11)
(dia-say s "2  with -b, a session on each makes the system first" 0 232 11)
(dia-say s "3  each machine starts a session of its own, that runs the command and says how it went" 0 248 11)
(dia-say s "4  a line a machine comes back to where it was asked" 0 264 11)
(diagram "rack_run" (dia-scene-doc s))
