;docs/ai_digest/rasterization.md: from a path to pixels
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'path (dia-box '("a path" "points, a line of no width") 170 44 grey 11 :first) 0 0)
(dia-put s 'stroke (dia-box '("stroke, gui/path" "widen it: joins at the corners," "caps at the ends") 190 62 blue 11 :first) 220 -9)
(dia-put s 'poly (dia-box '("polygons" "also what a fill or a glyph is") 190 44 grey 11 :first) 460 0)
(dia-put s 'edges (dia-box '(":set_edges" "an edge for each side," "cut to the clip") 170 62 green 11 :first) 470 90)
(dia-put s 'scan (dia-box '("the scanline loop" "8 lines to a row of pixels," "the edges crossed, in order") 190 62 green 11 :first) 230 90)
(dia-put s 'mask (dia-box '("the coverage mask" "one row: how much of each" "pixel is inside") 190 62 gold 11 :first) 0 90)
(dia-put s 'span (dia-box '(":span" "blends the colour into the" "pixmap by its cover") 190 62 blue 11 :first) 0 190)
(dia-join s 'path 'stroke "")
(dia-join s 'stroke 'poly "")
(dia-join s 'poly 'edges "")
(dia-join s 'edges 'scan "")
(dia-join s 'scan 'mask "")
(dia-join s 'mask 'span "")
(dia-say s "One row of mask is all the memory it needs, whatever the height of the picture." 220 226 12 :nil 0xff202428)
(diagram "raster_pipeline" (dia-scene-doc s))
