;docs/ai_digest/regexp_system.md: from a pattern to a match
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'pat (dia-box '("a pattern" "a(b|c)*d") 130 44 grey 11 :first) 0 0)
(dia-put s 'tok (dia-box '("tokens" "literals, operators," "character classes") 150 62 blue 11 :first) 170 -9)
(dia-put s 'post (dia-box '("postfix" "operators after what" "they act on") 150 62 blue 11 :first) 360 -9)
(dia-put s 'nfa (dia-box '("NFA instructions" "(:lit c) (:class s) (:wild)" "(:nil offset ...) (:assert)") 200 62 gold 11 :first) 550 -9)
(dia-put s 'run (dia-box '("the search" "every state it could be in," "stepped a character at a time") 200 62 green 11 :first) 550 100)
(dia-put s 'out (dia-box '("matches" "where each is, and each" "group within it") 150 62 grey 11 :first) 360 100)
(dia-join s 'pat 'tok "")
(dia-join s 'tok 'post "")
(dia-join s 'post 'nfa "")
(dia-join s 'nfa 'run "")
(dia-join s 'run 'out "")
(dia-say s "No going back over the text: the time it takes does not blow up on a hard pattern." 0 190 12 :nil 0xff202428)
(diagram "regexp_pipeline" (dia-scene-doc s))
