;docs/ai_digest/messages_and_routing.md: a message too big for a link goes as fragments that say where they belong
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'msg (dia-box '("a message bigger than lk_data_size") 380 34 gold 11) 0 0)
(dia-put s 'post (dia-box '("Postman, :sys_mail :out" "a session id, then slices") 190 44 grey 11 :first) 95 60)
(each (lambda (i)
	(dia-put s (sym (cat "f" (str i))) (dia-box (list "fragment" (cat "offset " (elem-get '("0" "L" "2L") i) ", total")) 120 40 gold 11 :first) (* i 130) 130)
	(dia-put s (sym (cat "c" (str i))) (dia-box (elem-get '("at 0" "at L" "at 2L") i) 120 34 (if (= i 1) 0xffffffff gold) 11) (* i 130) 230)
	(dia-join s (sym (cat "f" (str i))) (sym (cat "c" (str i))) ""))
	'(0 1 2))
(dia-join s 'msg 'post "")
(dia-join s 'post 'f1 "")
(dia-say s "by the links, any route, any order" 400 154 11)
(dia-say s "the parcel, :sys_mail :in: one buffer of the total length." 400 244 11)
(dia-say s "Each fragment is copied straight to its place by its offset," 400 260 11)
(dia-say s "and when the total has come the message is delivered." 400 276 11)
(diagram "routing_fragments" (dia-scene-doc s))
