;docs/ai_digest/messages_and_routing.md: a ping floods out, and each node keeps the links by which the origin is nearest
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'o (dia-box '("origin" "pings") 80 44 gold 11 :first) 0 70)
(dia-put s 'a (dia-box '("A" "1 hop") 70 44 blue 11 :first) 150 10)
(dia-put s 'b (dia-box '("B" "1 hop") 70 44 blue 11 :first) 150 130)
(dia-put s 'c (dia-box '("C" "2 hops, by A and by B") 170 44 green 11 :first) 300 70)
(dia-put s 'd (dia-box '("D" "3 hops") 70 44 blue 11 :first) 550 70)
(dia-join s 'o 'a "")
(dia-join s 'o 'b "")
(dia-join s 'a 'c "")
(dia-join s 'b 'c "")
(dia-join s 'c 'd "")
(dia-say s "a newer session, or fewer hops: take that link as the way, and pass the ping on" 0 210 11)
(dia-say s "the same hops by another link: keep that link as a way too, and pass nothing on" 0 226 11)
(dia-say s "So C has two ways to the origin, and mail for it is shared between them." 0 250 12 :nil 0xff202428)
(diagram "routing_flood" (dia-scene-doc s))
