;docs/ai_digest/shader_language.md: one shader source, and what each back end makes of it
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'src (dia-box '("a shader" "s-expressions, a .shader file") 190 44 grey 11 :first) 0 100)
(dia-put s 'check (dia-box '("lib/gpu/shader.inc" "read by the Lisp reader," "type checked in Lisp") 190 62 gold 11 :first) 230 91)
(each (lambda (i)
	(dia-put s (sym (cat "b" (str i))) (dia-box (elem-get '(("glsl.inc" "GLSL text") ("msl.inc" "Metal text") ("spirv.inc" "SPIR-V, for Vulkan") ("vp.inc" "VP code, a native function") ("cpu.inc" "a Lisp lambda")) i) 190 40 (if (< i 3) blue green) 11 :first) 470 (* i 50))
	(dia-join s 'check (sym (cat "b" (str i))) ""))
	'(0 1 2 3 4))
(dia-put s 'gpu (dia-box '("the GPU of the host" "through the SDL3 GUI driver") 210 44 grey 11 :first) 710 48)
(dia-put s 'farm (dia-box '("any CPU, no GPU" "farmed over the nodes") 210 44 grey 11 :first) 710 148)
(dia-put s 'ref (dia-box '("the reference" "the others are checked against") 210 44 grey 11 :first) 710 198)
(dia-join s 'b1 'gpu "")
(dia-join s 'b3 'farm "")
(dia-join s 'b4 'ref "")
(dia-join s 'src 'check "")
(dia-say s "The same source, the same inputs, the same picture." 0 266 12 :nil 0xff202428)
(diagram "shader_backends" (dia-scene-doc s))
