;docs/ai_digest/storage_service.md: the two maps of the store, and where a block is kept
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'path (dia-box '("a path" "the map that needs agreement") 200 44 gold 11 :first) 0 20)
(dia-put s 'object (dia-box '("an object" "the list of the names of its blocks") 240 44 blue 11 :first) 250 20)
(each (lambda (i)
	(dia-put s (sym (cat "b" (str i))) (dia-box (list "a block" "named by a hash of what is in it") 220 40 green 11 :first) 540 (* i 48))
	(dia-join s 'object (sym (cat "b" (str i))) ""))
	'(0 1 2))
(dia-join s 'path 'object "")
(dia-say s "where a block is kept: by a rule, no table" 0 170 12 :t 0xff202428)
(each (lambda (i)
	(dia-put s :nil (dia-box (list (cat "service " (elem-get '("C" "A" "E" "B" "D") i)) (cat "rank " (str (inc i)))) 110 40 (if (< i 3) green grey) 11 :first) (* i 120) 182))
	'(0 1 2 3 4))
(dia-say s "Each service ranks all that are up by a hash of the block's name and the service's id. The first three hold it." 0 246 11)
(dia-say s "All work out the same answer. One goes, the fourth is now one of the three and fetches a copy." 0 262 11)
(dia-say s "A write changes nothing where it is: new blocks, a new object, and the path is pointed at it." 0 286 12 :nil 0xff202428)
(diagram "storage_blocks" (dia-scene-doc s))
