;docs/ai_digest/streams.md: an :out stream and an :in stream, a pipe between two tasks
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'writer (dia-box '("the task that writes" "(write-blk) (stream-flush)") 180 44 grey 11 :first) 0 40)
(dia-put s 'out (dia-box '(":out stream" "(out-stream mbox)" "buffers, cuts into packets," "numbers each, seqnum") 180 78 blue 11 :first) 0 110)
(each (lambda (i) (dia-put s (sym (cat "m" (str i))) (dia-box (cat "seqnum " (elem-get '("2" "0" "1") i)) 90 26 gold 11) 250 (+ 96 (* i 34)))) '(0 1 2))
(dia-say s "messages, which may" 240 220 11)
(dia-say s "arrive in any order" 240 236 11)
(dia-put s 'in (dia-box '(":in stream" "(in-stream), its own mailbox" "puts them back in order," "sends acks") 190 78 green 11 :first) 410 110)
(dia-put s 'reader (dia-box '("the task that reads" "(read-line) (read-char)") 190 44 grey 11 :first) 410 40)
(dia-join s 'writer 'out "")
(dia-join s 'out 'm1 "")
(dia-join s 'm1 'in "")
(dia-join s 'in 'reader "")
(dia-say s "Closing the :out stream sends stopping, then stopped: the reader sees the end of the stream." 0 270 12 :nil 0xff202428)
(dia-say s "Neither task knows which node the other is on." 0 288 12 :nil 0xff202428)
(diagram "stream_pipe" (dia-scene-doc s))
