;docs/ai_digest/sync.md: two trees of hashes compared from the top, only where they differ is gone into
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6 red 0xfff7d7d7)
(defun tree-at (s tag x title)
	(dia-say s title x 12 12 :t 0xff202428)
	(dia-put s (sym (cat tag "_top")) (dia-box '("." "hash of all below") 130 40 red 11 :first) (+ x 70) 24)
	(dia-put s (sym (cat tag "_a")) (dia-box '("docs/" "differs") 110 40 red 11 :first) x 100)
	(dia-put s (sym (cat tag "_b")) (dia-box '("lib/" "the same") 110 40 green 11 :first) (+ x 140) 100)
	(dia-put s (sym (cat tag "_f")) (dia-box '("a file" "its SHA-256 differs") 130 40 red 11 :first) (- x 10) 176)
	(dia-join s (sym (cat tag "_top")) (sym (cat tag "_a")) "" :none)
	(dia-join s (sym (cat tag "_top")) (sym (cat tag "_b")) "" :none)
	(dia-join s (sym (cat tag "_a")) (sym (cat tag "_f")) "" :none))
(tree-at s "l" 10 "this machine")
(tree-at s "r" 430 "the other machine")
(dia-join s 'l_top 'r_top "the tops: 64 characters each way" :both)
(dia-join s 'l_f 'r_f "only this file is sent")
(dia-say s "lib/ and all under it is never asked about: its hash is the same." 0 250 12 :nil 0xff202428)
(dia-say s "A folder's hash is of the names and hashes of what is in it, so the top is one number for the whole tree." 0 268 12 :nil 0xff202428)
(diagram "sync_tree" (dia-scene-doc s))
