;docs/ai_digest/task_farming.md: a request to start a task rolls to the least loaded node near where it was sent
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'app (dia-box '("the app" "(open-child ... +kn_call_run)" "to any node, picked at random") 210 62 gold 11 :first) 0 20)
(dia-put s 'a (dia-box '("kernel" "9 tasks") 90 44 grey 11 :first) 270 29)
(dia-put s 'b (dia-box '("kernel" "6 tasks") 90 44 grey 11 :first) 420 29)
(dia-put s 'c (dia-box '("kernel" "2 tasks") 90 44 green 11 :first) 570 29)
(dia-put s 'd (dia-box '("kernel" "5 tasks") 90 44 grey 11 :first) 570 110)
(dia-join s 'app 'a "")
(dia-join s 'a 'b "fewer")
(dia-join s 'b 'c "fewer")
(dia-join s 'c 'd "" :none)
(dia-say s "started here: no neighbour has fewer" 420 96 11)
(dia-say s "Each kernel passes the request to a neighbour with fewer tasks, till none has. The load spreads itself." 0 180 12 :nil 0xff202428)
(diagram "task_downhill" (dia-scene-doc s))
