;docs/ai_digest/task_farming.md: a farm keeps a set number of workers alive across the network
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6 red 0xfff7d7d7)
(dia-put s 'app (dia-box '("the app" "(Farm create destroy size)" "(. farm :refresh timeout)") 190 62 gold 11 :first) 0 70)
(each (lambda (i)
	(dia-under s (dia-box "" 150 70 grey) 290 (* i 84))
	(dia-say s (cat "node " (str (inc i))) 298 (+ 16 (* i 84)) 11 :t)
	(dia-put s (sym (cat "w" (str i))) (dia-box (if (= i 1) '("worker" "gone, or too slow") '("worker" "a child task")) 126 40 (if (= i 1) red blue) 11 :first) 302 (+ 22 (* i 84)))
	(dia-join s 'app (sym (cat "w" (str i))) ""))
	'(0 1 2))
(dia-put s 'again (dia-box '("destroy, then create" "a new worker, on any node") 190 44 green 11 :first) 500 104)
(dia-join s 'w1 'again "")
(dia-say s "Each refresh the farm looks at when each worker last answered and whether its node is still there." 0 270 12 :nil 0xff202428)
(dia-say s "One that has gone is made again, so the number asked for is always at work." 0 288 12 :nil 0xff202428)
(diagram "task_farm" (dia-scene-doc s))
