;docs/ai_digest/test_cache.md: a test module is run again only if something it stands on has changed
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6 red 0xfff7d7d7)
(dia-put s 'mod (dia-box '("a test module" "tests/system/test_x.lisp") 190 44 gold 11 :first) 0 70)
(each (lambda (i)
	(dia-put s (sym (cat "d" (str i))) (dia-box (elem-get '("what it imports, and they do" "files and commands it names" "the boot image, the host, root.inc" "the suite itself") i) 230 30 grey 11) 240 (* i 40))
	(dia-join s 'mod (sym (cat "d" (str i))) "" :none))
	'(0 1 2 3))
(dia-put s 'hash (dia-box '("one hash" "of the hashes of them all") 170 44 blue 11 :first) 520 26)
(dia-put s 'cache (dia-box '("the cache" "obj/<cpu>/<abi>/tests/cache" "the hash it had, its counts") 190 62 grey 11 :first) 510 100)
(dia-put s 'same (dia-box '("the same" "not run, counts as they were") 190 44 green 11 :first) 730 20)
(dia-put s 'differs (dia-box '("differs, or it failed" "run again") 190 44 red 11 :first) 730 108)
(dia-join s 'd1 'hash "")
(dia-join s 'hash 'cache "" :both)
(dia-join s 'hash 'same "")
(dia-join s 'cache 'differs "")
(dia-say s "It is what is in a file that is hashed, not when it was written. A doc changed runs nothing, the boot image changed runs everything." 0 190 12 :nil 0xff202428)
(diagram "test_cache" (dia-scene-doc s))
