;docs/ai_digest/text_buffers.md: Buffer, Document and the Edit widget that shows one
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'buf (dia-box '("Buffer   lib/text/buffer.inc" "lines of text, undo and redo," "cursors: each (cx cy ax ay sx)") 250 62 green 11 :first) 0 150)
(dia-put s 'doc (dia-box '("Document   lib/text/document.inc" "is a Buffer, and knows words, lines," "paragraphs, blocks, forms") 250 62 green 11 :first) 0 50)
(dia-put s 'edit (dia-box '("Edit   gui/edit/lisp.inc" "a View with a Document in :buffer," "(defproxymethod) passes calls to it") 250 62 blue 11 :first) 330 50)
(dia-put s 'vdu (dia-box '("Vdu" "the text") 110 44 grey 11 :first) 330 159)
(dia-put s 'mask (dia-box '("Mask layers" "cursors, selection, found") 130 44 grey 11 :first) 450 159)
(dia-put s 'cmd (dia-box '("a command, a script" "no window at all") 250 44 gold 11 :first) 0 -50)
(dia-join s 'doc 'buf "comes of")
(dia-join s 'edit 'doc "has one")
(dia-join s 'edit 'vdu "")
(dia-join s 'edit 'mask "")
(dia-join s 'cmd 'doc "uses one")
(dia-say s "the model, no GUI" 0 232 11 :t 0xff202428)
(dia-say s "the view" 330 232 11 :t 0xff202428)
(diagram "text_layers" (dia-scene-doc s))
