;docs/ai_digest/text_stack.md: the layers of the text stack, the same commands over a widget or over a document with no screen
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'gui_app (dia-box '("GUI Editor, Viewer" "apps/tools/edit, viewer") 200 44 grey 11 :first) 0 0)
(dia-put s 'cli_app (dia-box '("edit, the command" "cmd/edit.lisp") 200 44 grey 11 :first) 300 0)
(dia-put s 'edit (dia-box '("lib/text/edit.inc" "(edit-insert) (edit-find) ..., on *edit*") 500 44 gold 11 :first) 0 84)
(dia-put s 'widget (dia-box '("Edit, the widget" "gui/edit/lisp.inc" "draws glyphs and masks") 200 62 blue 11 :first) 0 168)
(dia-put s 'doc (dia-box '("Document" "lib/text/document.inc" "no screen") 200 62 green 11 :first) 300 168)
(dia-put s 'buffer (dia-box '("Buffer" "lib/text/buffer.inc: the text, the cursors, undo") 500 44 green 11 :first) 0 270)
(dia-join s 'gui_app 'edit "")
(dia-join s 'cli_app 'edit "")
(dia-join s 'edit 'widget "*edit* is a widget")
(dia-join s 'edit 'doc "*edit* is a Document")
(dia-join s 'widget 'buffer "its :buffer")
(dia-join s 'doc 'buffer "is one")
(diagram "text_stack" (dia-scene-doc s))
