;docs/vm/vp_functions.md: the five sections of a function, and what in its header says where each is
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'header (dia-box '("header" "ln_fnode, length, entry, links, paths, stack, pathname") 380 46 gold 11 :first) 190 0)
(dia-put s 'code (dia-box '("code" "VP instructions, local calls are relative") 380 60 blue 11 :first) 190 46)
(dia-put s 'strings (dia-box '("string pool" "the strings the code uses") 380 40 grey 11 :first) 190 106)
(dia-put s 'links (dia-box '("external function Vtable" "a pointer for each function it calls outside itself") 380 46 green 11 :first) 190 146)
(dia-put s 'paths (dia-box '("path string pool" "the names of those functions, gone once it is bound") 380 46 grey 11 :first) 190 192)
(dia-put s 'f_entry (dia-box "entry" 90 26 0xffffffff 11) 0 62)
(dia-put s 'f_links (dia-box "links" 90 26 0xffffffff 11) 0 156)
(dia-put s 'f_paths (dia-box "paths" 90 26 0xffffffff 11) 0 202)
(dia-say s "offsets kept in the header" 0 110 11)
(dia-join s 'f_entry 'code "")
(dia-join s 'f_links 'links "")
(dia-join s 'f_paths 'paths "")
(dia-say s "Every call to another function goes through the Vtable: unbound, an entry is an offset to a path," 0 262 11)
(dia-say s "bound, it is the address of that function's code." 0 278 11)
(diagram "vp_function" (dia-scene-doc s))
