;docs/ai_digest/type_system.md: an object, its vtable, and the vtables of what it comes of
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'obj (dia-box '("an object, a :real" "slot 0: its vtable" "num_value ...") 170 62 gold 11 :first) 0 0)
(dia-put s 'v0 (dia-box '("vtable of :real" "slot 0: its parent" "methods ...") 150 62 blue 11 :first) 230 0)
(dia-put s 'v1 (dia-box '("vtable of :fixed" "slot 0: its parent" "methods ...") 150 62 blue 11 :first) 430 0)
(dia-put s 'v2 (dia-box '("vtable of :num" "slot 0: its parent" "methods ...") 150 62 blue 11 :first) 630 0)
(dia-put s 'v3 (dia-box '("vtable of :obj" "slot 0: 0" "methods ...") 150 62 grey 11 :first) 830 0)
(dia-join s 'obj 'v0 "")
(dia-join s 'v0 'v1 "")
(dia-join s 'v1 'v2 "")
(dia-join s 'v2 'v3 "")
(dia-say s "Is it a :num ? class/obj/inst_of walks this list and compares each pointer with the vtable of :num. As many steps as the class is deep." 0 84 11)
(dia-say s "A vtable has the header of a function and no code, so the boot linker binds its entries as it binds the calls of a function." 0 100 11)
(diagram "vtable_chain" (dia-scene-doc s))
