;docs/ai_digest/whiteboard.md: a touch, from the host to the thing on the board it landed on
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s 'host (dia-box '("the host's driver" "a device and a contact:" "id = device << 24 | contact") 190 62 grey 11 :first) 0 60)
(dia-put s 'gui (dia-box '("GUI service" "to the view it is on, or" "went down on") 170 62 grey 11 :first) 220 60)
(dia-put s 'view (dia-box '("Board-view" "to the document's space") 170 44 gold 11 :first) 420 69)
(dia-put s 'stage (dia-box '("Stage" "a pointer belongs to the actor" "it went down on, till it lifts") 200 62 gold 11 :first) 405 160)
(each (lambda (i)
	(dia-put s (sym (cat "a" (str i))) (dia-box (elem-get '(("Palette" "a wedge is picked") ("Instrument" "first two contacts hold it") ("Handles" "size, turn, an end") ("Surface" "each hand its own thing")) i) 190 40 (if (= i 3) green blue) 11 :first) 660 (+ 100 (* i 48)))
	(dia-join s 'stage (sym (cat "a" (str i))) ""))
	'(0 1 2 3))
(dia-say s "front" 860 124 11)
(dia-say s "back" 860 268 11)
(dia-put s 'bind (dia-box '("Bindings" "kind, device, buttons:" "tool, colour, width") 170 62 grey 11 :first) 420 262)
(dia-join s 'host 'gui "")
(dia-join s 'gui 'view "")
(dia-join s 'view 'stage "")
(dia-join s 'bind 'stage "what it is to be" :none)
(dia-say s "The stage only hands each contact to what it landed on. What the contacts mean is the actor's to say." 0 344 12 :nil 0xff202428)
(diagram "wb_pointers" (dia-scene-doc s))
