;docs/ai_digest/whiteboard.md: the parts of the whiteboard, each stands on those under it
(defq s (dia-scene) blue 0xffd7e6f7 green 0xffdff0d8 gold 0xffffe8a8 grey 0xfff2f4f6)
(dia-put s :nil (dia-box '("apps/media/whiteboard/" "the app: a window, toolbars, canvases") 300 44 gold 11 :first) 0 0)
(dia-put s :nil (dia-box '("cmd/cwb.lisp" "the command: no screen") 190 44 gold 11 :first) 310 0)
(dia-put s :nil (dia-box '("lib/image/cwb.inc" "a .cwb as a picture") 170 44 gold 11 :first) 510 0)
(dia-put s :nil (dia-box '("stripes.inc" "drawn by the nodes") 150 44 blue 11 :first) 0 50)
(dia-put s :nil (dia-box '("palette.inc" "the ring that opens") 150 44 blue 11 :first) 160 50)
(dia-put s :nil (dia-box '("tools.inc" "ruler, protractor, set square") 180 44 blue 11 :first) 320 50)
(dia-put s :nil (dia-box '("diagram.inc" "laid out by a program") 170 44 blue 11 :first) 510 50)
(dia-put s :nil (dia-box '("board.inc" "a document that is worked on: what is selected, undo, the surface and the handles") 500 44 green 11 :first) 0 100)
(dia-put s :nil (dia-box '("pointer.inc" "pointers, devices and contacts, a stage of actors, bindings") 500 44 green 11 :first) 0 150)
(dia-put s :nil (dia-box '("doc.inc" "the document: layers, shapes on SVG paths, groups, matrices, the .cwb file") 680 44 grey 11 :first) 0 200)
(dia-say s "Only the app needs a screen." 510 124 11)
(diagram "wb_parts" (dia-scene-doc s))
