;lisp bindings
(ffi nums-abs "class/nums/lisp_abs" 0)
; (nums-abs nums [nums]) -> nums
(ffi nums-scale "class/nums/lisp_scale" 0)
; (nums-scale nums scale [nums]) -> nums
(ffi nums-add "class/nums/lisp_add" 0)
; (nums-add nums nums [nums]) -> nums
(ffi nums-div "class/nums/lisp_div" 0)
; (nums-div nums nums [nums]) -> nums
(ffi nums-mod "class/nums/lisp_mod" 0)
; (nums-mod nums nums [nums]) -> nums
(ffi nums-mul "class/nums/lisp_mul" 0)
; (nums-mul nums nums [nums]) -> nums
(ffi nums-sub "class/nums/lisp_sub" 0)
; (nums-sub nums nums [nums]) -> nums
(ffi nums-min "class/nums/lisp_min" 0)
;(nums-min nums nums [nums]) -> nums
(ffi nums-max "class/nums/lisp_max" 0)
;(nums-max nums nums [nums]) -> nums
(ffi nums-sum "class/nums/lisp_sum" 0)
; (nums-sum nums) -> num
(ffi nums-dot "class/nums/lisp_dot" 0)
; (nums-dot nums nums) -> num
