;lisp bindings
(ffi "class/nums/lisp_abs" nums-abs)
; (nums-abs nums [nums]) -> nums
(ffi "class/nums/lisp_scale" nums-scale)
; (nums-scale nums scale [nums]) -> nums
(ffi "class/nums/lisp_add" nums-add)
; (nums-add nums nums [nums]) -> nums
(ffi "class/nums/lisp_div" nums-div)
; (nums-div nums nums [nums]) -> nums
(ffi "class/nums/lisp_mod" nums-mod)
; (nums-mod nums nums [nums]) -> nums
(ffi "class/nums/lisp_mul" nums-mul)
; (nums-mul nums nums [nums]) -> nums
(ffi "class/nums/lisp_sub" nums-sub)
; (nums-sub nums nums [nums]) -> nums
(ffi "class/nums/lisp_min" nums-min)
;(nums-min nums nums [nums]) -> nums
(ffi "class/nums/lisp_max" nums-max)
;(nums-max nums nums [nums]) -> nums
(ffi "class/nums/lisp_sum" nums-sum)
; (nums-sum nums) -> num
(ffi "class/nums/lisp_dot" nums-dot)
; (nums-dot nums nums) -> num
