(import "lib/collections/tree.inc")
(import "apps/games/onslaught/enums.inc")

(defq +config_file "usr/Guest/onslaught.tre")
(defq cfg (tree-load (file-stream +config_file)))
(defq *best_demo_data* (. cfg :find :demo))
(print "best demo data len:" (length *best_demo_data*))

(defq *playback_stream* (string-stream *best_demo_data*))
(defq *playback_keys* 0 *playback_count* 0)

(defun demo-play-keys ()
	(if (> *playback_count* 0)
		(progn
			(-- *playback_count*)
			*playback_keys*)
		(if (defq k (read-ubyte *playback_stream*))
			(if (defq c (read-ubyte *playback_stream*))
				(progn
					(setq *playback_keys* k *playback_count* c)
					*playback_keys*)
				-1)
			-1)))

; read header
(bind '(game_seed game_level map_idx enemy_army enemy_banner man_banner enemy_wizshot)
	(list (read-long *playback_stream*) (read-short *playback_stream*) (read-short *playback_stream*) (read-short *playback_stream*)
		  (read-short *playback_stream*) (read-short *playback_stream*) (read-short *playback_stream*)))
(bind '(man_power man_strength item_selected)
	(list (read-int *playback_stream*) (read-int *playback_stream*) (read-short *playback_stream*)))
(defq item_inv (list) i 0)
(while (< i 8)
	(push item_inv (read-short *playback_stream*))
	(++ i))
(defq item_use (list) i 0)
(while (< i 8)
	(push item_use (read-short *playback_stream*))
	(++ i))
(bind '(menu_diff menu_mode man_score mine_max enemy_max sky_top sky_bottom)
	(list (read-short *playback_stream*) (read-short *playback_stream*) (read-int *playback_stream*)
		  (read-short *playback_stream*) (read-short *playback_stream*) (read-long *playback_stream*) (read-long *playback_stream*)))

(print "header parsed successfully!")
(print "first 10 keys:")
(defq step 0)
(while (< step 10)
	(defq k (demo-play-keys))
	(print "step" step "key:" k "count remaining:" *playback_count*)
	(++ step))

(pii-exit)
