;lisp bindings
(ffi points-transform "class/points/lisp_transform" 0)
(ffi points-simplify "class/points/lisp_simplify" 0)
(ffi points-gen-quadratic "class/points/lisp_gen_quadratic" 0)
(ffi points-gen-cubic "class/points/lisp_gen_cubic" 0)
(ffi points-gen-arc "class/points/lisp_gen_arc" 0)
(ffi points-stroke-polylines "class/points/lisp_stroke_polylines" 0)
(ffi points-stroke-polygons "class/points/lisp_stroke_polygons" 0)
