;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Per User Preference Automator (pupa)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; edit and uncomment lines to customize
;(import 'index.inc)
;(defq images '("user/wallpaper/wallpaperok1024x768" "user/wallpaper/wallpaperok1920x1080.cpm"))
;(defq app_list '("calculator" "clock" "edit" "images" "terminal"))
;(defq auto_app_list '("edit"))
;
; TODO: implement functions for saving to and writing files in user directory
;not yet implemented (defq user_room '("user/pupa.inc" "user/usermap.inc" "user/welcome.msg"))
